WIP mid1/SOLID detailed questions
fullstack-development/developers-roadmap pull request #191
Opened 2020-04-16 04:37 UTC by Znack

Closes #35

2020-04-16 04:39 UTC, Znack commented
Обратите внимание, что в индексе первого мидла поставил структуры данных и принципы проектирования перед ООП и SOLID-ом. Также в SOLID добавил блок предварительных требований по двум темам (Prerequisites).

2020-04-16 04:53 UTC, kinda-neat commented on frontend/middle-1/solid.md
> +* How Information Hiding as a criterion for system decomposition is related to SRP?
for a system

2020-04-16 04:54 UTC, kinda-neat commented on frontend/middle-1/solid.md
> +* What does "reason to change" mean in the context of the SRP?
где-то SRP с the, где-то без

2020-04-20 12:48 UTC, Zarwlar commented
В источники можно ещё эту книгу добавить https://www.amazon.com/Adaptive-Code-via-principles-Developer/dp/0735683204 , там рассмотрены варианты применения различных пукнтов из солида на практике

2020-04-25 06:01 UTC, Znack commented
> В источники можно ещё эту книгу добавить https://www.amazon.com/Adaptive-Code-via-principles-Developer/dp/0735683204 , там рассмотрены варианты применения различных пукнтов из солида на практике

Прочитал главы про SOLID, в целом книжку полистал, мне понравилась. Кажется, что это неплохой вариант для тех, кто хочет из джуна перерасти в уверенного мидла :) Здесь и принципы нередко подробней рассматриваются, чем в большинстве статей, даже включая пейперы Мартина по некоторым темам, плюс сами примеры более практичные, и прикольно, что тут параллель проводится между эджайл разработкой и практиками написания поддерживаемого (гибкого) кода. 

Но я хз, прямо главы книги добавлять стоит ли. У нас насколько серьезно подходят при изучении темы к тому, чтобы прочитать прямо все ресурсы? Вообще у нас ресурсы в списках обычно идут как необязательные рекомендации, но в случае с этой книгой я бы особенно хотел подчеркнуть, что это факультатив и не супер строго обязательно изучать эти главы или даже книгу целиком :) Насколько я понимаю, @chmnkh вообще всегда все ресурсы читает, например

2020-04-25 06:14 UTC, Zarwlar commented
> У нас насколько серьезно подходят при изучении темы к тому, чтобы прочитать прямо все ресурсы?

А в чём именно проблема прочитать все ресурсы?

2020-04-25 07:51 UTC, chmnkh commented
> У нас насколько серьезно подходят при изучении темы к тому, чтобы прочитать прямо все ресурсы?

у нас они не являются обязательными же

если ресурс надо обязательным делать - то надо в вопросах явно и писать, типа "изучите это", т.е. прямо отдельным вопросом рассматривать

я читаю всё почти всегда: иногда какие-то ресурсы мне не заходят, и я к ним не возвращаюсь, или не дочитываю до конца, если серия статей какая-то, но пытаюсь я все просматривать как минимум

в целом я знаю людей, которые вообще забивают на ресурсы по большому счету, если думают, что могут и без них на вопросы ответить, поэтому я бы не рассчитывал, что ресурсы все читаются

2020-04-25 07:54 UTC, chmnkh commented
> А в чём именно проблема прочитать все ресурсы?

люди думают, что знают и без этого, и не хотят тратить время на прочтение чего-то, что не даст им новых знаний или мыслей

я не имею в виду, что люди плохие, это вполне себе резонное поведение, с какой-то стороны

2020-04-25 11:53 UTC, Znack commented
> А в чём именно проблема прочитать все ресурсы?

Ну лично у меня проблемы нет, но просто если все будут считать, что обязательно читать дословно все ресурсы, то может быть просто оверхэд и лишняя нагрузка для них. Короче я то в целом за то, чтобы добавить книгу, но я бы хотел быть уверен, что у нас все понимают, что ресурсы — вещь добровольная и надо к ним осознанно подходить. Видимо это даже стоит где-нибудь в блоке про то, как пользоваться картой, надо добавить

2020-04-26 04:12 UTC, chmnkh commented
> Видимо это даже стоит где-нибудь в блоке про то, как пользоваться картой, надо добавить

ну так в целом явно конечно будет, но из моего окружения, как минимум, до сих пор это вроде бы все понимали

2020-05-10 04:10 UTC, sk1e commented on frontend/middle-1/solid.md
> +* What is the difference between the SRP and Cohesion?
Какая разница между теплым и мягким? Может какая разница между модулем который следует принципу SR и модулем который следует принципу максимизации cohesion. 

И cohesion со строчной думаю будет грамотнее

2020-05-10 04:12 UTC, sk1e commented on frontend/middle-1/solid.md
> +* What is the difference between the SRP and Separation of concerns?
Separation тоже со строчной. И тоже separation of concerns **principle**

2020-05-11 05:25 UTC, sk1e commented on frontend/middle-1/solid.md
> +* Why the LSP principle requires to consider a extrinsic public behavior of a module to be consistent, not just a intrinsic private behavior?
Что такое консистентное поведение модуля? Модуль подтипа который сохраняет контракты супертипа? Если да, то вопрос сформулирован так, будто очевидно, что внутреннее поведение должно сохранять контракты и неочевидно, что внешнее поведение должно сохранять. Для меня очевидно именно для внешнего согласно определению behavioral subtype и неочевидно для внутреннего.

2020-10-05 13:39 UTC, Znack reviewed
@sk1e внёс кое-какие правки предложеннные и поотвечал на вопросы наконец, глянь плиз

2020-10-05 13:39 UTC, Znack commented on frontend/middle-1/solid.md
> +* How Information Hiding as a criterion for a system decomposition is related to the SRP?
ну у нас тут просто в теме Design есть Сокрытие информации, тут я то же самое имел в виду https://github.com/fullstack-development/developers-roadmap/blob/master/frontend/middle-1/design.md

2020-10-05 13:39 UTC, Znack commented on frontend/middle-1/solid.md
> +* What are the rules that balance the SRP in the opposite direction and help to avoid overdoing the decomposition?
С формулировкой согласен, что она не очень ясная и однозначная, я хз как лучше сформулировать. Идея тут в том, что SRP по сути предлагает всё бить и бить на части, однако есть другие принципы дизайна софта (не только из SOLID-а), которые нам наоборот говорят о том, что сильно бить не надо, так как эти принципы будут нарушены. Вот вопрос в том, какие это принципы и почему они будут нарушены, если слишком увлечься декомпозицией. Если у тебя есть предложения, как это грамотно и лаконично сформулировать, то буду рад :)

2020-10-05 13:39 UTC, Znack commented on frontend/middle-1/solid.md
> +* What is the difference between the SRP and Cohesion?
На Википедии "cohesion" везде со строчной, так что тут соглашусь с тобой :)

Про теплое и мягкое не совсем согласен, тут хоть и не совсем на одной прямой они лежат, но как минимум они и не ортогональны — есть много общего и есть принципиально разные моменты. В целом другими словами вопрос сформулировать можно, как примерно ты предлагаешь, только я бы так предложил — какая разница у тебя будет в приоритетах проеткирования если ты будешь максимально следовать SRP, или если максимально увеличивать cohesion? Так норм?

2020-10-05 13:39 UTC, Znack commented on frontend/middle-1/solid.md
> +* What is the difference between the SRP and Separation of concerns?
ну на Википедии хоть и со строчной (тут поправлю) употребляется, но при этом это самостоятельное название, без principle: https://en.wikipedia.org/wiki/Separation_of_concerns

> Separation of concerns results in more degrees of freedom...

2020-10-05 13:39 UTC, Znack commented on frontend/middle-1/solid.md
> +* [On the Criteria To Be Used in Decomposing Systems into Modules](https://www.cs.umd.edu/class/spring2003/cmsc838p/Design/criteria.pdf) (closely related to SRP)
Поменял, но вообще это распространенный пейпер, легко гуглится :)

2020-10-05 13:39 UTC, Znack commented on frontend/middle-1/solid.md
> +* How to make part of the application open for extension?
ну тут да, про технику. Можно заменить на "How to make module open for extension", пожалуй. Вроде особого смысла в "part of the application" я не вкладывал

2020-10-05 13:39 UTC, Znack commented on frontend/middle-1/solid.md
> +* Why public class properties violates the OCP principle?
Это есть в источниках, в частности в исходной статье [Мартина про OCP](https://drive.google.com/file/d/0BwhCYaYDn8EgN2M5MTkwM2EtNWFkZC00ZTI3LWFjZTUtNTFhZGZiYmUzODc1/view):

![image](https://user-images.githubusercontent.com/2928964/95085427-69903e80-0749-11eb-8a6f-c8e450aea4dd.png)

2020-10-05 13:39 UTC, Znack commented on frontend/middle-1/solid.md
> +* Why the LSP principle requires to consider a extrinsic public behavior of a module to be consistent, not just a intrinsic private behavior?
Если я правильно понял, то ты extrinsic и intrinsic бьешь по принципу супертип/подтип (то есть что extrinsic это про супертип, а intrinsic это про подтип). Но я тут (и вроде бы Мартин тоже, если я опять же правильно его понял) про другое: по сути intrinsic private behavior это правила и конвенции (в том числе интуитивно подразумеваемые, но не формализованные в коде), которые ты держишь в голове, когда работаешь в рамках одного этого модуля и которые касаются только внутренностей этого модуля. А extrinsic public это про то, что держат в голове и что подразуемвается, когда ты работаешь над внешним кодом, который импортирует и использует твой исходный модуль. То есть если ты пишешь функцию `registerProfile`, то ты думаешь в разные время в двух плоскостях — реализуя саму функцию ты думаешь о ее внутренней консистентности, чтобы там детали реализации все друг к другу подходили и все правила в том числе неформальные соблюдались, а потом когда ты используешь эту функцию в другом модуле, ты уже думаешь в другой плоскости, ты думаешь о том, как функция мапает входы на выходы, какие сайд эффекты произойдут и как повлият на твою систему, какие там закономерности при этом. 

Возможно, я криво опять выразился, тут опять же если обращаться к исходникам ([paper about LSP](https://drive.google.com/file/d/0BwhCYaYDn8EgNzAzZjA5ZmItNjU3NS00MzQ5LTkwYjMtMDJhNDU5ZTM0MTlh/view)), то вот аналогичный пример:
![image](https://user-images.githubusercontent.com/2928964/95086278-7eb99d00-074a-11eb-83b2-c401beafa3e6.png)

2020-11-30 15:21 UTC, sk1e requested changes

2020-11-30 15:21 UTC, sk1e commented on frontend/middle-1/solid.md
> +* Why the LSP principle requires to consider a extrinsic public behavior of a module to be consistent, not just a intrinsic private behavior?
Ты неправильно понял. В этой статье он говорит именно про сохранение инвариантов для подтипов в рамках модели супертипов/подтипов Б. Лисков. Но потом в Clean Architecture он признаёт что они были не правы и что принцип скорее про сохранение инвариантов для полиморфных интерфейсов.  Я думаю что он не прав и там и что принцип вообще высосан из пальца. Любому должно быть очевидно что если интерфейс задаёт инварианты на своё использование то нужно им следовать, а невозможность следования означение неправильное проектирование инварианта. И не важно будь это инвариант заданный в супертипе, в абстрактном интерфейсе или в простой функции которую мы используем. В первых двух лишь цена ошибки выше, как правило. В этом плане получается ты понял истинную суть принципа из описания неполноценного описания.

2020-11-30 15:44 UTC, sk1e commented on frontend/middle-1/solid.md
> +* What is the difference between the SRP and Cohesion?
Первое это принцип проектирования, второе это характеристика модуля. Подобные вопросы имеют смысл когда сравнивают одну характеристику с другой или один принцип с другим, но не характеристику с принципом.

> какая разница у тебя будет в приоритетах проеткирования если ты будешь максимально следовать SRP, или если максимально увеличивать cohesion

В твоей версии непонятно что такое приоритеты проектирования. Я бы ответил «в первом случае приоритет больше будет в дроблении ответственности, а во втором увеличение cohesion»

Моя версия выглядит понятнее и интереснее, чем она тебе не нравится?

2020-11-30 15:52 UTC, sk1e commented on frontend/middle-1/solid.md
> +* Why the LSP principle requires to consider a extrinsic public behavior of a module to be consistent, not just a intrinsic private behavior?
В общем после твоего ответа мне стало понятным что ты спрашивал в этом вопросе и особых претензий к формулировке уже нет.

2020-12-01 10:02 UTC, Znack commented on frontend/middle-1/solid.md
> +* Why public class properties violates the OCP principle?
Так то что у тебя есть computed поля не отменяет проблемы для обычных переменных. С ними всё то же самое. Если ты всё делаешь на методах и вычисляемых свойствах, то понятно, что проблемы нет, здесь же как раз и объясняется почему так и надо делать, а делать через обычные поля не надо

2020-12-01 10:06 UTC, Znack commented on frontend/middle-1/solid.md
> +* Why the LSP principle requires to consider a extrinsic public behavior of a module to be consistent, not just a intrinsic private behavior?
Только я так и не понял с чем ты не согласен с Мартином :) Он говорит, что надо следовать инвариантам и я не вижу высасывания из пальца по одной простой причине: всегда держать инварианты под контролем можно только путем осознанного избегания проблем, через дисциплину, никаких линтеров и правил компиляторов нет, которые бы это гарантировали. То есть надо явно знать что нельзя нарушать инварианты, надо понимать почему, осознавать какие именно проблемы могут появиться, чтобы этому правилу осознанно следваоть. Я понимаю, что для тебя это довольно банально с твоим опытом, но статьи рассчитаны не только на прожжённых на куче проектов разработчиков, но и на тех, кто 1-2 года в индустрии, им надо чётко разложить зачем не косячить :)

2020-12-01 10:10 UTC, Znack commented on frontend/middle-1/solid.md
> +* How Information Hiding as a criterion for a system decomposition is related to the SRP?
Хм, а я уже кстати забыл откуда я именно взял, но сейчас глянул пейпер ещё раз, да, как раз оттуда должен был, там примеры с тем как декомпозировать в плоскости "алгоритма" и в плоскости "скрытия информации"

2020-12-01 10:10 UTC, Znack commented on frontend/middle-1/solid.md
> +* How Information Hiding as a criterion for a system decomposition is related to the SRP?
Возможно, тут стоит уточнить, что именно в контексте этой статьи вопрос задан, как думаешь?

2020-12-01 10:11 UTC, Znack commented on frontend/middle-1/solid.md
> +* What are the rules that balance the SRP in the opposite direction and help to avoid overdoing the decomposition?
Гуд пропозал, спасибос

2020-12-01 10:23 UTC, Znack commented on frontend/middle-1/solid.md
> +* What is the difference between the SRP and Cohesion?
> Первое это принцип проектирования, второе это характеристика модуля. 

Ну с этим я согласен, просто ты в тонкости прямо залазишь, хотя я не против вопрос сформировать с учётом этого. У тебя есть формулировка вопроса, которая это учитывает? :)

2020-12-01 12:47 UTC, sk1e requested changes

2020-12-01 12:47 UTC, sk1e commented on frontend/middle-1/solid.md
> +* Why the LSP principle requires to consider a extrinsic public behavior of a module to be consistent, not just a intrinsic private behavior?
> Только я так и не понял с чем ты не согласен с Мартином :)

С тем что он ограничивает свой принцип на абстрактные интерфейсы которые имеют множество реализаций. Так же как он не был уникален для наследования также он и не уникален для реализаций абстрактных интерфейсов. Инварианты могут быть и у абсолютно любых интерфейсов и проблемы из-за их несоблюдения одинакового же рода. Акцент на Лисков с её подтипами/супертипами тут лишний.

Я думаю тут можно сделать более понятным и полезным, обозначив проблему неявных инвариантов в принципе, в том числе и для подтипов.

2020-12-01 12:50 UTC, sk1e commented on frontend/middle-1/solid.md
> +* Why public class properties violates the OCP principle?
Ты можешь попробовать как-то уточнить тут, что речь идёт про конкретный вид свойств и переменных, но я не знаю как

2020-12-01 12:50 UTC, sk1e commented on frontend/middle-1/solid.md
> +* What is the difference between the SRP and Cohesion?
Какая связь между SRP и cohesion?

2020-12-03 10:33 UTC, Znack commented on frontend/middle-1/solid.md
> +* How Information Hiding as a criterion for a system decomposition is related to the SRP?
> Ты не помнишь такой?

Не, такого не припомню совсем

> Я считаю что в карте не должны присутствовать плохо проработанные материалы в плане подачи информации.

Серёг, ну это вкусовщина уже пошла :) Хотя я согласен, что привязывать вопросы с конкретным источникам не очень хорошо, но конкретно тут мне кажется важной темой в обсуждении SRP еще затронить связь с декомпозицией и сокрытием информации.У тебя SRP говорит, что декомпозировать надо по reason to change, а тут мы это делаем пытаясь максимизировать гибкость, скрывая лишнее — эти два подхода почти всегда приводят к одинаковому результату, но подумать о различиях всё же полезно.

Давай тогда переформулируем так, чтобы отвязаться от статьи. Хотя тут ещё надо тогда чётко понять, почему текущая формулировка без знания статьи непонятна? Потому что она хоть и взята из пейпера, но в целом и без знания пейпера можно вопрос понять

2020-12-03 10:40 UTC, Znack commented on frontend/middle-1/solid.md
> +* Why public class properties violates the OCP principle?
Why mutable public class properties violate the OCP principle?

@sk1e как тебе?

2020-12-03 10:56 UTC, Znack commented on frontend/middle-1/solid.md
> +* Why the LSP principle requires to consider a extrinsic public behavior of a module to be consistent, not just a intrinsic private behavior?
Ааа, ну теперь понял. В целом, я тут с тобой согласен, но я думаю, что у тебя просто немного громкие заявления вроде 
> Я думаю что он не прав и там и что принцип вообще высосан из пальца

Я бы скорее выразился, что "принцип не учитывает все случаи" тогда, с этим я согласен, но я думаю, что это недостаточный повод сказать жёстко что автор "не прав" :)

Вообще, крутая тема для обсуждения, может её как отдельный вопрос добавить? Например, "распространяется ли этот принцип только на наследование и если нет, то на что еще"? Как тебе?

2020-12-05 11:14 UTC, sk1e commented on frontend/middle-1/solid.md
> +* Why the LSP principle requires to consider a extrinsic public behavior of a module to be consistent, not just a intrinsic private behavior?
Мне кажется не стоит, суть принципа завязана на критерии Лисков, даже в самом названии принципа есть Лисков :) В общем-то можно оставить как есть.

2020-12-07 06:58 UTC, Znack commented on frontend/middle-1/solid.md
> +* Why public class properties violates the OCP principle?
> change тут это мутация переменной?

Не, там в контексте OCP, где change об изменениях в проекте, а не о мутациях. Может быть и про мутации он тут, но я прямо уверен, что всё-таки про изменения в кодовой базе. Во втором случае я тоже уверен, что он про изменение в кодовой базе :) Но только тут к чему? По сути он здесь и говорит, что если ты юзаешь мутабельные переменные и потом меняешь (вот как раз тот change) бизнес-требования или еще как-то меняешь кодовую базу, затрагивая эту переменную, то тебе почти наверняка придётся учесть, как это скажется на всех клиенских модулях (классах, функциях), которые эту переменную юзали.

2020-12-07 08:09 UTC, chmnkh commented on frontend/middle-1/solid.md
> +* How Information Hiding as a criterion for a system decomposition is related to the SRP?
1. "Скрытие информации" само по себе не является критерием, является "степень скрытности" или что-то такое хз как сказать адекватно.
2. Постановке вопроса в духе "как А связано с Б" сильно широкая, ну т.е. именно здесь под такую формулировку много что ответить можно, и фиг знает, что именно нужно, как-то бы сузить здесь по идее.

2020-12-07 08:15 UTC, chmnkh commented on frontend/middle-1/solid.md
> +* What are the rules that balance the SRP in the opposite direction and help to avoid overdoing the decomposition?
насколько я могу судить, SRP не только про разделение, но и про объединение
т.е. я от Мартина 10 тысяч раз это слышал, как мне кажется
т.е. тут изначально как будто в вопросе заложено заблуждение, что SRP только про разделение, но не про объединение, но это не так

2020-12-07 08:19 UTC, chmnkh commented on frontend/middle-2/patterns.md
> +  * Как этот паттерн может помочь в следовании The Open Closed Principle?
ну тут-то the не нужен, наверное)

2020-12-07 08:32 UTC, sk1e commented on frontend/middle-1/solid.md
> +* Why public class properties violates the OCP principle?
Чем тогда публичные свойства тут особенны? Ты при изменении любого публичного интерфейса модуля получишь необходимость изменения кода клиентов этого модуля.

2020-12-07 08:34 UTC, sk1e commented on frontend/middle-1/solid.md
> +* Why public class properties violates the OCP principle?
Если ты изменишь код метода то тебе также надо учесть как это скажется на клиентских модулях

2020-12-08 08:25 UTC, sk1e commented on frontend/middle-2/patterns.md
> +  * Как этот паттерн может помочь в следовании The Open Closed Principle?
Тут на самом деле многие паттерны, если не все реализуют OCP. Да и другие принципы тоже.

2020-12-08 08:26 UTC, sk1e commented on frontend/middle-2/patterns.md
> +  * Как этот паттерн может помочь в следовании The Open Closed Principle?
лучше добавить вопрос о связи каждого из паттернов с каждым из принципов

2020-12-09 04:45 UTC, chmnkh commented on frontend/middle-2/patterns.md
> +  * Как этот паттерн может помочь в следовании The Open Closed Principle?
Серега, навверное стоило это отдельно написать, а то ты как будто мне отвечаешь, потом потеряться можно

2020-12-09 08:48 UTC, sk1e commented on frontend/middle-2/patterns.md
> +  * Как этот паттерн может помочь в следовании The Open Closed Principle?
Сорян, раньше вроде нельзя было дискашен открывать если строчку уже занимали другим дискашеном, поэтому в твой дискашен решил ворваться

2020-12-09 08:49 UTC, sk1e commented on frontend/middle-2/patterns.md
> +  * Как этот паттерн может помочь в следовании The Open Closed Principle?
Тут на самом деле многие паттерны, если не все реализуют OCP. Да и другие принципы тоже. Лучше добавить вопрос о связи каждого из паттернов с каждым из принципов

2020-12-09 09:29 UTC, chmnkh commented on frontend/middle-1/solid.md
> +TODO
а тут не забыто точно?)

2020-12-09 09:33 UTC, chmnkh commented on frontend/middle-1/solid.md
> +* Can we apply the SRP if we have no forecast how system can evolve (for example we are completely unfamiliar with the project)?
перед `how` как будто `of` нужно

а перед `system` `a`

2020-12-09 09:35 UTC, chmnkh commented on frontend/middle-1/solid.md
> +* Can the SRP be useful also for project written in FP paradigm?
мне кажется естественным `also` поставить перед `be`, но я не супер уверен, тут бы уточнить где-то еще

2020-12-09 09:35 UTC, chmnkh commented on frontend/middle-1/solid.md
> +* Can the SRP be useful also for project written in FP paradigm?
перед `project` `a` забыт

2020-12-09 09:47 UTC, chmnkh commented on frontend/middle-1/solid.md
> +* What does mean "open for extension" and "closed for modification"?
`what does татата mean?`
мин в конец

2020-12-09 09:48 UTC, chmnkh commented on frontend/middle-1/solid.md
> +* Why extensively used modules had better be closed for modification?
а че за had better be, почему такая форма именно?

2020-12-09 09:49 UTC, chmnkh commented on frontend/middle-1/solid.md
> +* How plugin-based architecture related to the OCP?
`How is`
ис потерял

2020-12-09 09:50 UTC, chmnkh commented on frontend/middle-1/solid.md
> +* Why public class properties violates the OCP principle?
violate, а не violates, множ. число потому что

2020-12-09 09:51 UTC, chmnkh commented on frontend/middle-1/solid.md
> +* Can the OCP be useful also for project written in FP style?
тут тоже олсо перед би хочется поставить

2020-12-09 09:51 UTC, chmnkh commented on frontend/middle-1/solid.md
> +* How violation of the LSP principle also violate OCP?
Liskov Substitution Principle principle?)

2020-12-09 09:52 UTC, chmnkh commented on frontend/middle-1/solid.md
> +* What is The Liskov Substitution Principle?
the с маленькой бквы

2020-12-09 09:52 UTC, chmnkh commented on frontend/middle-1/solid.md
> +## The Open Closed Principle (OCP)
а нафига нам в тайтлах the нужен? выглядит странно

2020-12-09 09:56 UTC, chmnkh commented on frontend/middle-1/solid.md
> +* Why the LSP principle requires to consider a extrinsic public behavior of a module to be consistent, not just a intrinsic private behavior?
Liskov Substitution Principle principle?)

2020-12-09 09:56 UTC, chmnkh commented on frontend/middle-1/solid.md
> +* Why the LSP principle requires to consider a extrinsic public behavior of a module to be consistent, not just a intrinsic private behavior?
an extrinsic, не `a`

2020-12-09 09:57 UTC, chmnkh commented on frontend/middle-1/solid.md
> +* Why the LSP principle requires to consider a extrinsic public behavior of a module to be consistent, not just a intrinsic private behavior?
intrinsic - то же самое

2020-12-09 09:58 UTC, chmnkh commented on frontend/middle-1/solid.md
> +* Can the LSP be useful also for project written in FP style?
тут та же фигня с `also` перед `be`

2020-12-09 10:05 UTC, chmnkh commented on frontend/middle-1/solid.md
> +* What is The Interface Segregation Principle?
the с маленькой

2020-12-09 10:05 UTC, chmnkh commented on frontend/middle-1/solid.md
> +* How the ISP helps to solve problem of classes that implement non-cohesive interfaces?
`a` problem

2020-12-09 10:06 UTC, chmnkh commented on frontend/middle-1/solid.md
> +* How can violation of the ISP principle also violate LSP?
"нарушение может нарушить" - это фигня какая-то, нарушение может привести к нарушению - это да

2020-12-09 10:07 UTC, chmnkh commented on frontend/middle-1/solid.md
> +* Can the ISP be useful also for project written in FP style?
also be

2020-12-09 10:08 UTC, chmnkh commented on frontend/middle-1/solid.md
> +* What is The Dependency Inversion Principle?
the с маленькой

2020-12-09 10:08 UTC, chmnkh commented on frontend/middle-1/solid.md
> +* Are Cross-cutting Concerns always "low-level"? Why?
а зачем Cross-cutting Concerns с больших букв?

2020-12-09 10:10 UTC, chmnkh commented on frontend/middle-1/solid.md
> +* Where should abstraction be declared that connect high-level and low-level modules? Can it be declared in low-level module and then be imported in high-level one?
> declared in low-level module

in `a` low-level module

> in high-level one

in `a` ...

2020-12-09 10:10 UTC, chmnkh commented on frontend/middle-1/solid.md
> +* What is The Stable Dependencies Principle (SDP) and how is it related with the DIP?
the с большой

2020-12-09 10:12 UTC, chmnkh commented on frontend/middle-1/solid.md
> +* Why modules with high stability tend to be less volatile?
Why `do`

2020-12-09 10:12 UTC, chmnkh commented on frontend/middle-1/solid.md
> +* Why modules with the least stability are called irresponsible and dependent?
Why `are`, а дальше `are` убрать

2020-12-14 10:11 UTC, Znack commented on frontend/middle-1/solid.md
> +* Why extensively used modules had better be closed for modification?
Ну типа "почему таким модулям лучше быть такими, а не такими", здесь в таком контексте :) Но вообще лучше переформулировать с "prefer" наверное или с "advantages" как нибудь

2020-12-14 10:13 UTC, Znack commented on frontend/middle-1/solid.md
> +* Why extensively used modules had better be closed for modification?
> What are the advantages to make extensively used modules closed for modification?

Вот так сделал

2020-12-14 10:19 UTC, Znack commented on frontend/middle-1/solid.md
> +## The Open Closed Principle (OCP)
У Мартина в том числе в тайталх используется артикль :)

![image](https://user-images.githubusercontent.com/2928964/102069462-66dc5480-3e30-11eb-8d40-27ca49827e7c.png)

Ну и я не увидел здесь проблемы, решил сделать так же. мне самому сложно ответить, как лучше, но так как минмиум норм :)

2020-12-14 10:23 UTC, Znack commented on frontend/middle-1/solid.md
> +* How can violation of the ISP principle also violate LSP?
Не сразу понял, что ты имел в виду, но вроде допёр, поправь, если не так плиз

2020-12-14 10:24 UTC, Znack commented on frontend/middle-1/solid.md
> +* Are Cross-cutting Concerns always "low-level"? Why?
🤷

2020-12-14 10:58 UTC, Znack commented on frontend/middle-1/solid.md
> +* Why public class properties violates the OCP principle?
Серег, ты точно читал пейперы Мартина и в целом про ооп? :) 

![image](https://user-images.githubusercontent.com/2928964/102073297-ad807d80-3e35-11eb-82ad-46e3dcc9041b.png)

Просто методы класса и созданы для абстрагирования — ты тоже стараешься публичные методы по минимуму менять, но даже меняя ты там контракты и инварианты ещё можешь сохарнять в рабочем состоянии, но при изменении состояния ты мало чем можешь абстрагироваться, ты по сути меняешь мясо класса, а это уже не очень хорошо. Поэтому для стейта вообще в ооп принято целиком закрываться, а для методов публичность доступна, но тебе надо руками стараться абстрагироваться максимально грамотно

2020-12-14 11:00 UTC, Znack commented on frontend/middle-1/solid.md
> +* Why public class properties violates the OCP principle?
Мне кажется, мы уходим немного не туда :) У тебя по сути уже начались споры не по форме вопроса, а по контенту — у меня ощущение, что ты споришь с Мартином, а не со мной, я думаю, это уже часть ответа (то есть как раз в качестве ответа твои эти рассуждения хорошо подходят)

2020-12-14 11:08 UTC, Znack commented on frontend/middle-1/solid.md
> +* What are the rules that balance the SRP in the opposite direction and help to avoid overdoing the decomposition?
Ну я здесь в том числе и упомянул, что именно в контексте разделения модулей (вторая часть вопроса) — то есть да, SRP в том числе про объединение, но здесь другой подсмысл :)

2020-12-14 11:12 UTC, Znack commented on frontend/middle-2/patterns.md
> +  * Как этот паттерн может помочь в следовании The Open Closed Principle?
ну хз, остальные просто это скорее косвенно связано, а стратегия это прямая реализация этого принципа

2020-12-14 11:13 UTC, Znack commented on frontend/middle-2/patterns.md
> +  * Как этот паттерн может помочь в следовании The Open Closed Principle?
> ну тут-то the не нужен, наверное)


А вот хз, почему думаешь, что не надо? Потому что остальная часть на русском? :)

2020-12-14 11:13 UTC, Znack commented on frontend/middle-1/solid.md
> +TODO
Хм, забыто :(

2020-12-14 11:26 UTC, Znack commented on frontend/middle-1/solid.md
> +TODO
Добавил

2020-12-14 11:29 UTC, Znack commented on frontend/middle-1/solid.md
> +* How Information Hiding as a criterion for a system decomposition is related to the SRP?
Честно, тут сложный вопрос, давайте вместе подискутируем. У [Мартина статья](https://blog.cleancoder.com/uncle-bob/2014/05/08/SingleReponsibilityPrinciple.html) начинается как раз со сравнения с этим критерием из статьи Парнаса, мне это тоже показалось интересной темой на обсуждение. Но я понимаю, что у этого вопроса есть несколько минусов: завязка на пейпер Парнаса, не очень понятная формулировка, если не изучены конкретные ресурсы (хотя и довольно классические для темы этой), кривость формулировки, которую хз как исправить.

@sk1e @chmnkh вы в итоге думаете, что лучше вопрос кикнуть, чем пытаться его выправить?

2020-12-14 20:13 UTC, sk1e commented on frontend/middle-1/solid.md
> +* Why public class properties violates the OCP principle?
У меня и к в форме и к содержанию претензии. Постараюсь максимально коротко и с пруфами. Касательно формы:

1. Сами свойства не могут нарушать этот принцип, может нарушать их использование в коде. Т.е. не "почему  публичные свойства нарушают OCP?", а "почему использование в коде публичных свойств нарушает OCP?"
2. Публичные методы тоже нарушают OCP как и любой другой публичный интерфейс. Если ты используешь какой-то интерфейс в каком-то модуле и этот интерфейс меняется, то очевидно что и код этого модуля нужно поменять. То, про что ты говоришь, и про что Мартин там говорит, это то, что **больше множество потенциальных изменений** в клиентском модуле когда стейт оформлен публичным свойством по сравнению со стейтом в виде функции гетера/сетера, т.к. код функций можно дополнять. Т.е. надо так "почему определение доступа/чтения состояния через публичные свойства приводит к нарушению OCP в большей степени, чем определение доступа/чтения состояния через функции?"
3. На самом деле и не в большей степени приводит к нарушению OCP если у тебя в языке поддерживаются вычисляемые свойства. Ты можешь объявить публичное свойство и когда тебе нужно будет поменять его на гетер/сетер то спокойно меняешь не затрагивая клиентские модули.  

Так что, если формулировать прям корректно, то так: "почему определение доступа/чтения состояния через публичные свойства приводит к нарушению OCP в большей степени, чем определение доступа/чтения состояния через функции в языках которые не поддерживают вычисляемые свойства?"

По содержанию я не согласен с вот этим 

![image](https://user-images.githubusercontent.com/16105414/102125181-d75c9300-3e7b-11eb-823e-9080387e6df7.png)

Он тут утверждает как надо писать код, приводит пруфы почему это может быть полезно, но не приводит пруфов почему это всегда полезно и почему это не может иметь вреда. Я могу привести пруф, что такая конвенция может быть вредна.

Допустим у нас есть класс который производит какие-то численные вычисления и вычисления зависят от состояния этого класса, состояние также включает числа, а меняет его клиентский модуль. Также, мы можем быть довольно серьёзно уверены что никакая логика над состоянием нам не нужна, либо мы просто используем современный язык который позволяет её добавить через вычисляемые свойства. Ещё допустим что нам часто нужно выполнять такие операции надо состоянием.

```
obj.prop1 += 1;
obj.prop2 *= 2;
obj.calculate();
```

Если мы будем следовать правилу 

> Member variables should never be known to any other class,

то у нас получится клиентские модули превратятся в такое:

```
obj.setProp1(obj.prop1 + 1);
obj.setProp2(obj.prop2 * 2);
obj.calculate();
```

При условии что такого кода много, то это объективно негативно скажется на нём. Код будет читаться сложнее, поддержка будет дороже значительно. Какая от этого польза? Никакая. Мы просто делаем так как нам сказали в статье.

Я это к тому, что все статьи которые тут приведены не имеют строгих пруфов своей правоты и поэтому могут быть не правы, а на те места, к которым есть вопросы лучше не ссылаться. Либо ссылаться вместе с вопросами. У нас карта **развития**, а не набор вопросов на которые нужно дать ответы ссылаясь на ненаучные пейперы и авторитет чужого мнения вместо логики и собственных рассуждений.

2020-12-14 20:27 UTC, sk1e commented on frontend/middle-2/patterns.md
> +  * Как этот паттерн может помочь в следовании The Open Closed Principle?
Как ты опредляешь тут косвенность? Посмотри внимательнее, тут все кроме синглтона его реализуют в одинаковой мере. Стратегия самая простая просто. Все эти патерны вертятся над полиморфизмом,  а полиморфизм позволяет тебе добавлять модули для различных типов, тем самым «расширяя» код модуля которые этот полиморфизм использует.

2020-12-14 20:33 UTC, sk1e commented on frontend/middle-2/patterns.md
> +  * Как этот паттерн может помочь в следовании The Open Closed Principle?
Вот ещё пруфы 

![image](https://user-images.githubusercontent.com/16105414/102132237-ee07e780-3e85-11eb-8219-9e4670e46d07.png)
![image](https://user-images.githubusercontent.com/16105414/102132292-024be480-3e86-11eb-915a-4b74696f712b.png)
![image](https://user-images.githubusercontent.com/16105414/102132347-168fe180-3e86-11eb-8b83-1b54f11a2a33.png)

2020-12-29 05:52 UTC, Znack commented on frontend/middle-1/solid.md
> +* Why public class properties violates the OCP principle?
Серег, в целом согласен про детали формулировок, что, например, это использование нарушает и тд. Но по части критики самого принципа у меня ощущение, что ты не совсем хорошо понял ООП либо намеренно его искажаешь: ты берешь антипаттерны из ООП, которые явно в сообществе приняты как практики, которых надо избегать, и на них доказываешь "смотрите как плохо" :) Ну да, геттеры/сеттеры голые использовать действительно плохо и твои примеры действительно смотрятся как ущербные, я бы не хотел такой код поддерживать, но это и не совсем грамотное ООП :) Я могу так же вкривь\вкось писать в ФП стиле, а потом показывать его лисперам и хаскеллистам "смотрите, как ужасно ваше ФП" 😆 

Например, вот с твоим кусков кода:
```
obj.prop1 += 1;
obj.prop2 *= 2;
obj.calculate();
```
тут надо понять, какую цель в целом ты пытаешься этим кодом решить именно с верхнеуровневой точки зрения. Условно, какая бизнес-логика скрывается за этими тремя строчками? допустим, если это рассчёт зп, то тогда у класса должен быть метод `calculateSalary`, а не два публичных свойства и метод `calculate`. То есть проблема с этим кодом действительно есть, ты правильно написал, что это всё очень плохо пахнет, но прикол в том, что Мартин изначально не про такой код писал, я в этом уверен, потому что для этого кода есть уже несколько других принятых соглашений почему так писать не стоит (и как стоит, что например класс должен моделировать объект реального мира и что методы должны это поведение моделировать, а не просто экспоузить низкоуровневые перменные состояния или голые методы `calculate`). 

Короче мы тут долго можем спорить, давай либо созвон как-нибудь устроим, либо в офисе встретимся и обсудим, я тебе расскажу, а то очень затянется :) И тогда предлагаю переформулировать вот так и зарезолвить дискашен: "почему определение доступа/чтения состояния через публичные свойства приводит к нарушению OCP" (про вычислимые и методы предлагаю не упоминать именно тут, можно это отдельным доп вопросом спросить для тех кто хочет подумать)

2020-12-29 05:53 UTC, Znack commented on frontend/middle-2/patterns.md
> +  * Как этот паттерн может помочь в следовании The Open Closed Principle?
Серег, блин, я забыл, а мы когда голосом это обсуждали, ты сказал, что понял лучше, можешь формулировку того, как понял, написать? :)

2021-01-01 22:52 UTC, sk1e commented on frontend/middle-2/patterns.md
> +  * Как этот паттерн может помочь в следовании The Open Closed Principle?
Я понял твои "ощущения" что "стратегия" в большей степени к расширению функциональности модуля: если взять каноничный по солиду модуль, то единственный способ расширить именно функциональность именно каноничного модуля можно только через неё. Другие патерны больше к расширению, например, совместимости с другими модулями или к созданию нового модуля на основе абстрактного. Но тогда из вопроса возникнет мнение что в ООП OCP это только про стратегию. Если понимать принцип в более общем виде, то мы должны стараться добавлять новый код, а не редактировать существуюствующий. Даже в самой статье Мартина пример OCP приводится на template method, а не стратегии. В любом случае будет полезно подумать как тот или иной патерн связан с солидом чтобы лучше понять обе темы.

2021-01-01 23:11 UTC, sk1e commented on frontend/middle-1/solid.md
> +* Why public class properties violates the OCP principle?
Я ж сказал что там про какие-нибудь численные штуки, в смысле что-то математическое, а не корпоративных моделей вроде зп, там значительно сильнее необходимость к изменению состояния через подобные арифметические операторы.

> почему определение доступа/чтения состояния через публичные свойства приводит к нарушению OCP
го так :)

2021-01-01 23:52 UTC, sk1e commented on frontend/middle-1/solid.md
> +* How Information Hiding as a criterion for a system decomposition is related to the SRP?
Можно заменить "Information Hiding" на "difficult design decisions hiding", тогда вопрос конкретизируется. Можно ещё к каждому вопросу приклеплять ссылку на ресурс, чтобы связь была прочнее и понятно где вопрос раскрывается

2021-01-11 10:18 UTC, Znack commented on frontend/middle-2/patterns.md
> +  * Как этот паттерн может помочь в следовании The Open Closed Principle?
Вообще, я подумал, что и правда тут лучше явно про каждый паттерн спросить о связи с SOLID и не привязываться к стратегии и именно OCP :) Переделал, теперь к каждому паттерну есть вопрос о связи с SOLID

2021-01-11 10:19 UTC, Znack commented on frontend/middle-2/patterns.md
> +  * Как этот паттерн может помочь в следовании The Open Closed Principle?
уже неактуально :)

2021-01-11 10:23 UTC, Znack commented on frontend/middle-1/solid.md
> +* How Information Hiding as a criterion for a system decomposition is related to the SRP?
Мне кажется, это прямо запутает :) Тем более в самом пейпере Information Hiding тоже напрямую как термин используется: 
![image](https://user-images.githubusercontent.com/2928964/104169144-aeef9680-5431-11eb-8d94-7766b16f7424.png)

Я вообще переформулировал вопрос, сделал там явную ссылку на пейпер, так что теперь все должно быть более очевидно и понятно, предлагаю тут зарезолвить :)

2021-01-11 10:30 UTC, Znack commented on frontend/middle-1/solid.md
> +* Why public class properties violates the OCP principle?
Окей, сделано 👌

2021-01-11 10:32 UTC, sk1e approved these changes

2021-01-11 10:40 UTC, Znack commented
![image](https://user-images.githubusercontent.com/2928964/104170618-03941100-5434-11eb-8b3a-8527bd543f2c.png)

@sk1e поставил аппрув!

2021-01-11 10:46 UTC, chmnkh approved these changes

2021-01-11 14:14 UTC, merged