Immutable data - Junior1
fullstack-development/developers-roadmap pull request #224
Opened 2020-08-03 16:07 UTC by Gmihtt

Added questions about immutable data

2020-08-04 07:06 UTC, Znack commented on backend/junior-1/haskell.md
> +    Which data in Haskell is immutable? Example of an immutable data structure.
давай явно спросим, какие операции с такими данными возможны и явно о том, что делать если надо данные апдейтнуть

2020-08-04 20:40 UTC, Gmihtt commented on backend/junior-1/haskell.md
> +    Which data in Haskell is immutable? Example of an immutable data structure.
Обновил

2020-08-06 16:31 UTC, kelizarov commented on backend/junior-1/haskell.md
> +  * Which data in Haskell is immutable? Example of an immutable data structure.
Вопрос с подвохом) Есть ли смысл такое спрашивать учитывая что хаскель функциональный язык? Может как-нибудь перефразировать вопрос?

2020-10-09 05:49 UTC, vladimirbokor commented on backend/junior-1/haskell.md
> +  * How can you work with immutable data structures? What can you do if you need to update this data structure?
Не совсем понимаю, что хочется услышать в ответ здесь

2020-10-12 12:44 UTC, Gmihtt commented on backend/junior-1/haskell.md
> +  * Which data in Haskell is immutable? Example of an immutable data structure.
Можно явно попросить объяснить в чем состоит иммутабельность данных на примере работы со списком, как вариант

2020-10-12 12:46 UTC, Gmihtt commented on backend/junior-1/haskell.md
> +  * How can you work with immutable data structures? What can you do if you need to update this data structure?
Что если, к примеру, тебе надо изменить какое-то поле у записи или элемент списка или все т.п., то ты пересоздаешь объект на основе старого, а не изменяешь его

2020-10-12 12:49 UTC, kelizarov commented on backend/junior-1/haskell.md
> +  * Which data in Haskell is immutable? Example of an immutable data structure.
Ну вот так да можно переформулировать :)

2020-10-12 12:49 UTC, kelizarov commented on backend/junior-1/haskell.md
> +  * How can you work with immutable data structures? What can you do if you need to update this data structure?
Я думаю тогда стоит прямо спросить, что вот у нас есть тип и надо обновить один из его рекордов. Как это можно сделать.

2020-10-12 13:31 UTC, Gmihtt commented on backend/junior-1/haskell.md
> +  * How can you work with immutable data structures? What can you do if you need to update this data structure?
Поменял, проверьте)

2020-10-14 03:23 UTC, olgaklimenko requested changes

2020-10-14 03:23 UTC, olgaklimenko commented on backend/junior-1/haskell.md
> +    How to do it, if all the data in Haskell is immutable. Give examples for the record and the list.
Кстати, у нас тут неспроста все вопросы задаются "как вопросы", для поддержания стиля можно и тут переделать на подобное: `Can you give some examples ....?`

Плюс предлагаю перефразировать вопрос:

   * What to do, if you need to update the data structure? How to do it, if all the data in Haskell is immutable.  -> Is there any way to update the data structure in Haskell?

2020-10-14 03:33 UTC, olgaklimenko commented on backend/junior-1/haskell.md
> +  * What is immutable data?
Тут мб переделаем на группу вопросов, раз уж начали спрашивать, спросим поподробнее?

What is an immutability concept? 
How does it differ from mutability? 
Can you list the pros and cons of both concepts? 
What concept is using in Haskell?

+ не добавлены источники по этой теме, можно накидать простых статей и объяснений со stackoverflow

2020-12-01 11:15 UTC, Geksanit commented
@Gmihtt привет, можешь доделать этот пр?

2020-12-02 08:26 UTC, Gmihtt commented
Обновил вопросы и добавил линки

2020-12-02 09:33 UTC, olgaklimenko approved these changes

2020-12-02 10:31 UTC, Znack approved these changes

2020-12-02 10:38 UTC, kelizarov requested changes

2020-12-02 10:38 UTC, kelizarov commented on backend/junior-1/haskell.md
> +  * What to do, if you need to update the data structure? How to do it, if all the data in Haskell is immutable. -> Is there any way to update the data structure in Haskell?
Здесь в постановке вопроса лежит ответ на предыдущий вопрос выше. 

Запятые в обоих предложениях излишне, в англ они немного по-другому работают. Я бы перефразировал вопрос вот так бы:
```
How can you update values in immutable data structure?
```

2020-12-02 10:38 UTC, kelizarov commented on backend/junior-1/haskell.md
> +  * Can you give some examples for the record and the list?
Не совсем понятно что здесь хочется услышать в ответ? Как обновить данные в иммутабельных рекордах или списках? Или что-то другое?

2020-12-02 14:45 UTC, Gmihtt commented on backend/junior-1/haskell.md
> +  * Can you give some examples for the record and the list?
Предполагалось, что тут надо будет на базовых штуках языка показать как работать с иммутабельными структурами в хаскеле

2020-12-02 14:45 UTC, Gmihtt commented on backend/junior-1/haskell.md
> +  * What to do, if you need to update the data structure? How to do it, if all the data in Haskell is immutable. -> Is there any way to update the data structure in Haskell?
Да, хорошее перефразирование

2020-12-04 08:31 UTC, kelizarov approved these changes

2020-12-04 08:36 UTC, merged