Backend/mid-1/Add design section
fullstack-development/developers-roadmap pull request #244
Opened 2020-11-04 10:49 UTC by stanislav-az

Новые изменения для мидла-1 бекенда:

1. вопросы про проектирование (design) вынесены в общие в фронтом

2. дописано какие именно главы СИКП нужно сдать на первом уровне

2020-11-04 11:09 UTC, Znack requested changes

2020-11-04 11:09 UTC, Znack commented on shared/middle-1/README.md
> +- [Базовые принципы проектирования](../../shared/middle-1/design.md)
Если на этой странице все на английском, то тогда и название пункта тоже на английский перевести лучше :)

2020-11-04 11:09 UTC, Znack commented on backend/middle-1/README.md
> +  3.  Modularity, Objects, and State
А зачем по пустой строке под каждым пунктом? :) Как думаешь, стоит ли еще явно подписать, что именно "Chapter 1", или так тоже норм?

2020-11-15 09:18 UTC, stanislav-az commented on backend/middle-1/README.md
> +  3.  Modularity, Objects, and State
Почему-то нумерация не отображается правильно в превью, если не ставить пустые строки

2020-11-15 09:18 UTC, stanislav-az commented on backend/middle-1/README.md
> +  3.  Modularity, Objects, and State
Chapter 1 напишу лучше

2020-11-16 04:46 UTC, Znack approved these changes

2020-11-16 04:47 UTC, Znack commented on backend/middle-1/README.md
> +  TODO: add questions
тут про вопросы из самого СИКПа? Тогда лучше явно обозначить, что "move questions about SICP from rizzoma"

2020-11-19 06:06 UTC, olgaklimenko requested changes

2020-11-19 06:06 UTC, olgaklimenko commented on backend/middle-1/README.md
> +  TODO: add questions
Не нашла в риззоме вопросы по Sicp, есть только задание про интерепретатор.

![image](https://user-images.githubusercontent.com/11536292/99627983-dba5b400-2a67-11eb-9d18-da5f7ebf6163.png)

Если они там есть, почему тогда сразу их не перенести в этом ПР?

2020-11-19 15:10 UTC, Znack commented on backend/middle-1/README.md
> +  TODO: add questions
У нас вопросы в топике фронтендеров, там прямо подробно расписано. Вопросов очень много, их лучше отдельным ПРом сделать 👍

2020-11-23 10:16 UTC, stanislav-az commented on backend/middle-1/README.md
> +  TODO: add questions
Я лучше буду переносить после сдачи, чтобы сразу исправить или добавить вопросы

2020-11-23 10:36 UTC, olgaklimenko approved these changes

2020-11-24 13:25 UTC, chmnkh approved these changes

2020-11-24 15:51 UTC, merged