Update React Jun2
fullstack-development/developers-roadmap pull request #260
Opened 2020-12-09 10:53 UTC by iatsdotfatr

2020-12-09 17:27 UTC, Znack commented on frontend/junior-2/react.md
> +* Какие существуют правила при работе с хуками? Для чего предназначены следующие хуки и как с ними работать: useState, useReducer, useEffect?
названия всех хуков, типа `useState` надо в обратные кавычки обернуть, так как это код

2020-12-09 17:31 UTC, Znack commented
Вот и настала эпоха хуков в нашей карте... мы долго сопротивлялись, но теперь пора принять новую реальность...

2020-12-09 17:36 UTC, Znack commented
Я бы ещё добавил вопросы про то, какие ограничения по работе с хуками (типа что нельзя в циклах, условиях и тд юзать), и как тут линтер помогает. И если я правильно помню, линтер не помогает с более хитрыми условиями, типа когда хук случайно заюзал внутри функции высшего порядка, например, в `map`, тоже про это лучше спросить явно

2020-12-10 04:17 UTC, iatsdotfatr commented
> Я бы ещё добавил вопросы про то, какие ограничения по работе с хуками (типа что нельзя в циклах, условиях и тд юзать), и как тут линтер помогает. И если я правильно помню, линтер не помогает с более хитрыми условиями, типа когда хук случайно заюзал внутри функции высшего порядка, например, в `map`, тоже про это лучше спросить явно

Ну я про правила работы с хуками поставил вопрос, в документации для этого есть целый раздел, линтер в нем тоже упоминается.

2020-12-10 07:33 UTC, Znack commented
> Ну я про правила работы с хуками поставил вопрос, в документации для этого есть целый раздел, линтер в нем тоже упоминается.

Ааа, точно, как-то пропустил :)

2020-12-10 15:41 UTC, AkhmadBabaev commented on frontend/junior-2/react.md
> +* Какие существуют правила при работе с хуками? Для чего предназначены следующие хуки и как с ними работать: `useState`, `useReducer`, `useEffect`?
Согласно [требованиям к оформлению вопросов](https://github.com/fullstack-development/developers-roadmap/blob/master/requirements.md) предпочтительнее будет написать так

*  Какие существуют правила при работе с хуками? Для чего предназначены хуки `useState`, `useReducer`, `useEffect`? Как с ними работать ?

2020-12-10 15:55 UTC, AkhmadBabaev commented on frontend/junior-2/react.md
> +* Какие существуют правила при работе с хуками? Для чего предназначены следующие хуки и как с ними работать: `useState`, `useReducer`, `useEffect`?
Вопрос _Какие существуют правила при работе с хуками?_ выглядит как самостоятельный вопрос, думаю его лучше сделать отдельным вопросом.

2020-12-10 17:28 UTC, iatsdotfatr commented on frontend/junior-2/react.md
> +* Какие существуют правила при работе с хуками? Для чего предназначены следующие хуки и как с ними работать: `useState`, `useReducer`, `useEffect`?
> И если я правильно помню, линтер не помогает с более хитрыми условиями, типа когда хук случайно заюзал внутри функции высшего порядка, например, в `map`, тоже про это лучше спросить явно

Похоже, настроили для этого случая

![Screenshot from 2020-12-10 23-23-08](https://user-images.githubusercontent.com/51824674/101807400-4619b380-3b3f-11eb-8bdb-54cb755c5f00.png)

2020-12-10 17:54 UTC, AkhmadBabaev approved these changes

2020-12-12 11:58 UTC, Znack approved these changes

2020-12-14 07:17 UTC, performanceArtist requested changes

2020-12-14 07:17 UTC, performanceArtist commented on frontend/junior-2/react.md
> +  * Для чего предназначены хуки `useState`, `useReducer`, `useEffect`? Как с ними работать?
Нужно добавить `useMemo` и `useCallback`.

2020-12-14 07:17 UTC, performanceArtist commented on frontend/junior-2/react.md
> +  * Допустим, текущим значением состояния, созданным с помощью `useState`, является объект. Если обновить текущее состояние другим объектом, произойдет ли слияние данных объектов?
Странный вопрос. Это даже по типам проверку не пройдет, если свойства не опциональные. Были случаи путаницы с `this.setState`?

2020-12-14 07:17 UTC, performanceArtist commented on frontend/junior-2/react.md
> +  * Какие и почему существуют правила при работе с хуками?
>Какие и почему

Звучит топорно, лучше разделить. Или по-моему достаточно про правила спросить - думаю, и так ясно, что нужно это обосновать.

2020-12-14 07:17 UTC, performanceArtist commented on frontend/junior-2/react.md
> +  * Как выполнить очистку эффекта в `useEffect`?
Я бы еще спросил когда очистка вызовется при наличие deps и отсутствии + когда само содержание useEffect вызывается.

2020-12-14 07:36 UTC, performanceArtist commented on frontend/junior-2/react.md
> +  * Для чего предназначены хуки `useState`, `useReducer`, `useEffect`? Как с ними работать?
Хотя раз весь перформанс на третьем, то наверное ок. Хотя странно выходит - как по мне, `useMemo` самый используемый из хуков.

2020-12-14 08:05 UTC, iatsdotfatr commented on frontend/junior-2/react.md
> +  * Допустим, текущим значением состояния, созданным с помощью `useState`, является объект. Если обновить текущее состояние другим объектом, произойдет ли слияние данных объектов?
Добавил этот вопрос по аналогии c setState

2020-12-14 08:09 UTC, iatsdotfatr commented on frontend/junior-2/react.md
> +  * Какие и почему существуют правила при работе с хуками?
Согласен, что звучит не очень, можно написать второй вопрос вроде "почему существуют эти правила?". Мне тоже так кажется, но кому-то может быть неочевидно, а проверяющие, например, забудут уточнить.

2020-12-14 09:21 UTC, sk1e requested changes

2020-12-14 09:21 UTC, sk1e commented on frontend/junior-2/react.md
> +  * Как выполнить очистку эффекта в `useEffect`?
Во-первых, эффект это сайд-эффект, такой термин лучше не сокращать. Во-вторых слово «очистка» неприменимо к сайд-эффекту, сайд-эффект это не то, что можно «очистить».

Лучше спросить что возвращает колбэк переданный в `useEffect`.

2020-12-14 10:28 UTC, iatsdotfatr commented on frontend/junior-2/react.md
> +  * Как выполнить очистку эффекта в `useEffect`?
Терминологию использовал из документации, но, возможно, неточный перевод, там говорится как "clean up after effect", так и "clean up an effect". Колбэк может и ничего не возвращать, можно спросить, что может вернуть колбэк, хотя это тоже не совсем неточно.

2020-12-14 10:37 UTC, sk1e commented on frontend/junior-2/react.md
> +  * Как выполнить очистку эффекта в `useEffect`?
Ну «ничего» тоже можно возвращать, поэтому можно и таким вопрос оставить :) В документации тоже могут ошибаться, лучше не тащить эти ошибки к нам.

2020-12-14 10:44 UTC, iatsdotfatr commented on frontend/junior-2/react.md
> +  * Как выполнить очистку эффекта в `useEffect`?
Тогда переформулирую в  "Что может возвращать коллбэк, передаваемый в useEffect?", думаю, в таком случае будет очевидно, про что именно вопрос.

2021-01-01 21:53 UTC, sk1e approved these changes

2021-01-11 09:50 UTC, performanceArtist approved these changes

2021-01-11 09:56 UTC, merged