Moving Code Complete onto middle-1 as a set of questions and sources
fullstack-development/developers-roadmap pull request #263
Opened 2020-12-25 14:15 UTC by olegromashin

Based on https://github.com/fullstack-development/developers-roadmap/issues/242

2020-12-26 03:08 UTC, chmnkh commented on shared/middle-1/design.md
> +* Как проведение аналогий может помочь лучше понять задачу и объяснить её другим?
а причем здесь проектирование?

2020-12-26 03:09 UTC, chmnkh commented on shared/middle-1/design.md
> +* В чём заключается принцип Парето? Как этот принцип применяется к времени, которое программа выполняет определённые участки кода? Как этот принцип отражает время, которое программист тратит на напис
> к времени
к**о** времени

2020-12-26 03:10 UTC, chmnkh commented on shared/middle-1/design.md
> +* Какие бывают стратегии проектирования?
если тут какие-то конкретные стратегии подразумеваются, то имхо их лучше перечислить, потому что не понятно наверняка, что тут отвечать нужно

2020-12-26 03:12 UTC, chmnkh commented on shared/middle-1/design.md
> +* Почему важно заранее продумать требования? Можно ли перестараться?
о каких требованиях речь? те требования, которые у меня в голове возникают, не от разработчиков идут, тогда не понятно, зачем этот вопрос здесь

ну либо я не о тех требованиях думаю

2020-12-26 09:19 UTC, olegromashin commented on shared/middle-1/design.md
> +* Почему важно заранее продумать требования? Можно ли перестараться?
Речь о требованиях к продукту\задаче, чтобы правильно спроектировать решение. Думаешь лучше изменить формулировку?

2020-12-26 09:31 UTC, olegromashin commented on shared/middle-1/design.md
> +* Как проведение аналогий может помочь лучше понять задачу и объяснить её другим?
Ну здесь мейби придумать как по-другому вопрос составить, но суть в том, что, если не можешь сразу найти решение какой-то задачи, то можно попробовать привести аналогию и тем самым подтолкнуть себя в верном направлении. В источниках к этому вопросу вторая глава МакКоннелла.

2020-12-26 10:32 UTC, stanislav-az requested changes

2020-12-26 10:32 UTC, stanislav-az commented on shared/middle-1/design.md
>  # Базовые принципы проектирования
Может для вопросов из Макконнелла сделать отдельный раздел? По нему просто довольно абстрактные вопросы некоторые, хотя бы будет понятно где искать на такое ответ

2020-12-26 10:32 UTC, stanislav-az commented on shared/middle-1/design.md
>  # Базовые принципы проектирования
В смысле, чтобы это был подраздел в # Базовые принципы проектирования

2020-12-26 10:32 UTC, stanislav-az commented on shared/middle-1/design.md
> +* Как проведение аналогий может помочь лучше понять задачу и объяснить её другим?
Я думаю что вопрос норм, так как первый этап при проектировании - определить проблему (задачу). Про этапы, кстати тоже мб спросить

2020-12-26 10:32 UTC, stanislav-az commented on shared/middle-1/design.md
> +* Почему важно заранее продумать требования? Можно ли перестараться?
Я тоже думаю, что лучше максимально подробно расписать к чему это относится, что речь идет о требованиях к проектируемому приложению

2020-12-26 10:35 UTC, olegromashin commented on shared/middle-1/design.md
> +* Какие бывают стратегии проектирования?
https://github.com/fullstack-development/developers-roadmap/pull/263/files#diff-27d8c97d2b0329abba58eec3b3f0ccd84695fc3d90a3a95f2482cd352c06bbd4R35
Лучше?

2020-12-26 10:44 UTC, olegromashin commented on shared/middle-1/design.md
> +* Почему важно заранее продумать требования? Можно ли перестараться?
https://github.com/fullstack-development/developers-roadmap/pull/263/files#diff-27d8c97d2b0329abba58eec3b3f0ccd84695fc3d90a3a95f2482cd352c06bbd4R4
Норм?

2020-12-26 10:53 UTC, olegromashin commented on shared/middle-1/design.md
>  # Базовые принципы проектирования
Как вариант. Мне в принципе без разницы, хотелось бы ещё чьё-нибудь мнение на этот счёт)
@Znack @kelizarov @olgaklimenko @chmnkh

2020-12-27 04:31 UTC, chmnkh commented on shared/middle-1/design.md
> +* Как проведение аналогий может помочь лучше понять задачу и объяснить её другим?
> если не можешь сразу найти решение какой-то задачи, то можно попробовать привести аналогию и тем самым подтолкнуть себя в верном направлении

как это работает вообще? можешь пример привести?

я понимаю примеры у Макконела, в духе, "чуваку приснилось что-то/он что-то увидел/услышал и т.д., и его осенило", но это в любом случае довольно случайная вещь

каким образом ты собрался с помощью аналогии придти к решению какой-то конкретной задачи?

часть про "объяснение с помощью метафоры" мне понятна и с ней я согласен, но как объяснение чего-то и проектирование связаны - я хз

2020-12-27 04:31 UTC, chmnkh commented on shared/middle-1/design.md
> +* Как проведение аналогий может помочь лучше понять задачу и объяснить её другим?
> Я думаю что вопрос норм, так как первый этап при проектировании - определить проблему (задачу). 

выше написал

> Про этапы, кстати тоже мб спросить

в чем практическая ценность?

2020-12-27 04:36 UTC, chmnkh commented on shared/middle-1/design.md
> +* Какие бывают стратегии проектирования?
а зачем это нужно?

2020-12-27 04:45 UTC, chmnkh commented on shared/middle-1/design.md
> +* Почему важно заранее продумать требования? Можно ли перестараться?
я не сильно понял, как этот вопрос связан с данным топиком (проектированием) и обычными разработчиками 

т.е. в целом можно сказать, что определение требований - это часть проектирования, но, как мне кажется, в данном топике проектирование рассматривается в первую очередь со стороны разработчиков

требования же к продукту разработчики практически не определяют, если не брать в расчет какие-то отдельные небольшие кейсы

т.е. ответ на этот вопрос должны те знать, в чьи обязанности входит определение требований, а это не обычные разрабы

2020-12-27 04:49 UTC, chmnkh commented on shared/middle-1/design.md
>  # Базовые принципы проектирования
как по мне, все вопросы, кроме вопроса про Complexity, и Во(ни)сходящее проектирование (правда нафиг это надо я не знаю, ну я там и отписался) вообще не в тему тут заехали, не понятно, причем тут проектирование, как будто не знали, куда вопросы приармянить, и засунули сюда их)

ну и у меня в целом куча вопросов на тему того, зачем это в карте, некоторые вопросы, например про принцип Парето, напоминают вопросы в духе "интересный факт", а зачем они нужны, я не понимаю

2020-12-27 04:50 UTC, chmnkh commented on shared/middle-1/design.md
>  # Базовые принципы проектирования
На миддлах и так достаточно вопросов, по которым можно в околофилософские обсуждения удариться на 2 часа, еще принципа Парето тут не хватало))

2020-12-29 08:46 UTC, olegromashin commented on shared/middle-1/design.md
> +* Почему важно заранее продумать требования? Можно ли перестараться?
Ну тому кто будет проектировать надо явно понимать, что какие-то пропуски в требованиях могут повлечь за собой последствия. И при необходимости уточнять их.

2020-12-29 08:49 UTC, olegromashin commented on shared/middle-1/design.md
> +* Какие бывают стратегии проектирования?
Не знаю насколько это используется на практике. @stanislav-az твоя идея, ответь :)

2020-12-29 09:06 UTC, olegromashin commented on shared/middle-1/design.md
> +* Как проведение аналогий может помочь лучше понять задачу и объяснить её другим?
Ну в книге помимо того, что кому-то что-то приснилось, ещё про то, как менеджеру правильно объяснить, что на проеткирование надо выделить время.
Не знаю, опять же, как часто на практике можно спосотавить свою архитектурную проблему с чем-то и прийти к решению. @kelizarov предложил добавить это, может лучше объяснит.

2020-12-30 07:05 UTC, kelizarov commented
А почему вопросы и темы из книги макконела перешли из джуна-3 на мидла-1? И почему книгу убрали тоже из джуна-3? Мне казалось что мы хотели просто выделить на какие главы стоит обратить внимания и какие мы будем спрашивать. При этом я бы хотел чтобы книгу все равно полностью прочли, просто принимать ее полностью не будем.

CC @Znack @olegromashin @stanislav-az

2021-01-01 12:29 UTC, iatsdotfatr commented
> А почему вопросы и темы из книги макконела перешли из джуна-3 на мидла-1?

\+ 
Тоже не понимаю, зачем тащить куски из книги на мидла. Насколько помню, предполагалось или выпилить книгу вообще, добавив ее только как источник информации, или убрать из сдачи некоторые главы, или все оставить как есть.

2021-01-11 05:59 UTC, Znack commented
Не, мы решили немного по-другому, просто о выпиливании книги мы в итоге не договаривались, мы еще в ишью пришли к такому варианту: сама книга целиком убирается как обяхаетльный элемент из обучения, некоторые темы из книги мы оставляем в явном виде в карте, так как эти темы хотелось бы чтобы были изучены. При этом мы эти темы добавляем как вопросы, которые можно не только по книге изучить, можно просто нагуглить любые другие ресурсы, а сами главы из книги просто как опциональные ресурсы становятся в помощь для изучения.

Короче книгу целиком из обязательного обучения лучше убрать, потому что книга для многих прямо оверхед часто и многие вещи все равно дублируются с Ремеслом. Однако самые интересные и уникальные темы из книги можно просто добавить в виде вопросов, и те, кому книга тяжело идёт могут другие источники взять.

2021-01-11 06:00 UTC, Znack commented
Но это всё я выше описал просто как вариант, который оптимальней всего показался. Если у вас есть предложения, которые еще круче к ситуации подходят, предлагайте, но просьба их хорошо обосновать :) Просто "книга нужна, я считаю надо оставить" не прокатит, потому что это мы уже обсуждали и отклонили :)

2021-01-11 06:09 UTC, Znack commented
Возможно, нам всё же стоит провести созвон, там подробно обсудить ещё раз почему именно к такому решению пришли, какие еще варианты есть и может придумать новые

2021-01-11 08:29 UTC, kelizarov commented
@Znack @olegromashin @stanislav-az Ну давайте тогда по-этапно это решим, чтобы изменения долго не висели в воздухе. Раз мы сошлись на том чтобы убрать книгу как обязательное чтиво, тогда давайте для начала уберем ее. А вопросы лучше проработать отдельным ПР'ом, так как для них нам понадобиться найти чуть больше источников чем сама книга, ведь в ней довольно поверхостно все расписано для ознакомления. 

Что думаете?

2021-01-11 09:46 UTC, Znack commented
Кстати да, звучит разумно. Давайте завтра этот вариант обсудим подробней на созвоне тогда 👍

2021-02-22 06:45 UTC, olegromashin commented
https://github.com/fullstack-development/developers-roadmap/issues/242#issuecomment-773216639

2021-02-22 06:45 UTC, closed without merging