creation of the topic about coding and design on jun-3
fullstack-development/developers-roadmap pull request #282
Opened 2021-02-17 12:18 UTC by olegromashin

Ишью - https://github.com/fullstack-development/developers-roadmap/issues/242
Предыдущий ПР с обсуждениями - https://github.com/fullstack-development/developers-roadmap/pull/263

2021-02-17 13:23 UTC, kelizarov requested changes

2021-02-17 13:23 UTC, kelizarov commented on shared/junior-3/codingAndDesign.md
> +* What is Coupling?
Думаю стоит добавить вопрос о `What 'low coupling, high cohesion' means?`

2021-02-17 13:23 UTC, kelizarov commented on shared/junior-3/codingAndDesign.md
> +* Is it important to write code with maximum optimization? When you have to start thinking about forcing optimization? Why?
Давай так лучше: `Is premature optimaztion harmfull on early stage of development? Explain why?`

2021-02-17 13:23 UTC, kelizarov commented on shared/junior-3/codingAndDesign.md
> +* Is it important to write code with maximum optimization? When you have to start thinking about forcing optimization? Why?
Еще бы добавить вопросы о защитном программировании и зачем оно нужно.

2021-02-17 13:23 UTC, kelizarov commented on shared/junior-3/codingAndDesign.md
> +* Why it is important to think over requirements in advance? Is it possible to overdo it?
Нужно уточнить требования чего: задачи, проекта, разработки? А то будет непонятно на что отвечать тут.

2021-02-17 13:23 UTC, kelizarov commented on shared/junior-3/codingAndDesign.md
> +* Explain the following practices of design: Iterate, Divide and Conquer, Top-Down and Bottom-Up design approaches.
`practices of design` -> `design prinicples`

2021-02-17 13:23 UTC, kelizarov commented on shared/junior-3/codingAndDesign.md
> +* [The Open Closed Principle](https://blog.cleancoder.com/uncle-bob/2014/05/12/TheOpenClosedPrinciple.html)
Не совсем понятно как этот ресурс должен помочь в ответе на вопросы. Тут рассказывается про принцип открытости/закрытости модули или части системы, и что они означают в разработке.

Если мы хотим, чтобы на 3-м джуне знали такой принции и как он работает, то тогда стоит явно спросить об этом.

2021-02-17 13:32 UTC, chmnkh requested changes

2021-02-17 13:32 UTC, chmnkh commented on shared/junior-3/codingAndDesign.md
> +Consolidate most important and common coding principles for all programming languages. Get acquainted with basic notions of design. All design questions do not require detailed answers. This topic im
**the** most

2021-02-17 13:32 UTC, chmnkh commented on shared/junior-3/codingAndDesign.md
> +Consolidate most important and common coding principles for all programming languages. Get acquainted with basic notions of design. All design questions do not require detailed answers. This topic im
В первых двух предложениях подлежащего нету, я бы добавил. Сильно, но не до конца, уверен, что без подлежащего нельзя.

2021-02-17 13:32 UTC, chmnkh commented on shared/junior-3/codingAndDesign.md
> +Consolidate most important and common coding principles for all programming languages. Get acquainted with basic notions of design. All design questions do not require detailed answers. This topic im
> for all programming languages

мне кажется, что эта фраза - шум, можно без нее обойтись

2021-02-17 13:32 UTC, chmnkh commented on shared/junior-3/codingAndDesign.md
> +Consolidate most important and common coding principles for all programming languages. Get acquainted with basic notions of design. All design questions do not require detailed answers. This topic im
их вообще видимо в одно можно объединить через союз

2021-02-17 13:32 UTC, chmnkh commented on shared/junior-3/codingAndDesign.md
> +Consolidate most important and common coding principles for all programming languages. Get acquainted with basic notions of design. All design questions do not require detailed answers. This topic im
> This topic implies preparation for [basic design principles]

1. топик не может ничего имплаить, топик - это просто набор текста, он просто существует
2. некорректно вообще использовано: можно было бы сказать, что "сдача топика на миддле implies сдачу топика на 3 джуне", что означало бы, что когда мы сдаем на миддле дизайн, мы уже сдали дизайн на 3 джуне
вот примеры: Democracy implies free elections, Socialism implies equality [отсюда](https://dictionary.cambridge.org/dictionary/english/imply)


учитывая эти 2 пункта, сейчас написана какая-то мутота)

2021-02-17 13:32 UTC, chmnkh commented on shared/junior-3/codingAndDesign.md
> +* Why it is important to test code? What are black-box testing and white-box testing?
why **is it**

2021-02-17 13:32 UTC, chmnkh commented on shared/junior-3/codingAndDesign.md
> +* What is the difference between the following types of testing: unit testing, component testing, integration testing, regression testing, system testing?
неудобно написан вопрос: я бы тут списком каждый вид тестирования написал, перед этим сформулировав как-то общий вопрос

2021-02-17 13:32 UTC, chmnkh commented on shared/junior-3/codingAndDesign.md
> +* Is it important to write code with maximum optimization? When you have to start thinking about forcing optimization? Why?
> forcing optimization

так точно говорят?)

2021-02-17 13:32 UTC, chmnkh commented on shared/junior-3/codingAndDesign.md
> +* Numbers in General - Subchapter 12.1 of Code Complete by Steve McConnell
мне кажется можно 1 раз написать COde complete by steve mcconell и сделать лист с главами, а то какая-то копипаста странная, тыжпрограммист(

2021-02-17 13:32 UTC, chmnkh commented on shared/junior-3/codingAndDesign.md
> +* Why it is important to think over requirements in advance? Is it possible to overdo it?
Why **is it**

2021-02-17 13:32 UTC, chmnkh commented on shared/junior-3/codingAndDesign.md
> +* Why it is important to think over requirements in advance? Is it possible to overdo it?
что значит "заранее обдумать требования?"

звучит сильно абстрактно

2021-02-17 13:32 UTC, chmnkh commented on shared/junior-3/codingAndDesign.md
> +* Explain the following practices of design: Iterate, Divide and Conquer, Top-Down and Bottom-Up design approaches.
лучше все чт опосле двоеточия списком оформить, читаемее будет

2021-02-17 13:41 UTC, olegromashin commented on shared/junior-3/codingAndDesign.md
> +* [The Open Closed Principle](https://blog.cleancoder.com/uncle-bob/2014/05/12/TheOpenClosedPrinciple.html)
Это случайно залетело, когда я структуру документа копипастил из другого топика) уберу

2021-02-18 07:04 UTC, Znack commented on frontend/junior-3/README.md
> +- [Базовые принципы кодирования и проектирования](../../shared/junior-3/codingAndDesign.md)
`basicCodingAndDesignPrinciples.md` — может так как нибудь? :)

2021-02-18 07:05 UTC, Znack commented on shared/junior-3/codingAndDesign.md
> +Consolidate most important and common coding principles for all programming languages. Get acquainted with basic notions of design. All design questions do not require detailed answers. This topic im
Да хз, я бы на самом деле оставил чтобы подчеркнуть всеприменимость. Это может быть неочевидно джуниору

2021-02-19 02:08 UTC, chmnkh commented on shared/junior-3/codingAndDesign.md
> +Consolidate most important and common coding principles for all programming languages. Get acquainted with basic notions of design. All design questions do not require detailed answers. This topic im
ну да, согласен

2021-02-20 09:52 UTC, stanislav-az requested changes

2021-02-20 09:52 UTC, stanislav-az commented on shared/junior-3/codingAndDesign.md
> +Consolidate most important and common coding principles for all programming languages. Get acquainted with basic notions of design. All design questions do not require detailed answers. This topic im
Мне кажется вот так писать нельзя
> All design questions do not require detailed answers

Ответ все равно должен быть подробный. Он просто не имеет единственно правильного, 100% точного, ожидаемого ответа. Поэтому я бы так и написал. Что здесь нужно изложить своё понимание, высказать мнение, и обсудить этот вопрос с принимающими.

2021-02-20 09:52 UTC, stanislav-az commented on shared/junior-3/codingAndDesign.md
> +Consolidate most important and common coding principles for all programming languages. Get acquainted with basic notions of design. All design questions do not require detailed answers. This topic im
> This topic implies preparation for

implies это значит нужно сначала изучить и сдать тему проектирования на мидла-1, а потом прочитать этот раздел? Мне кажется, ты здесь хотел написать, что этот раздел вводный к design mid-1.

2021-02-20 09:52 UTC, stanislav-az commented on shared/junior-3/codingAndDesign.md
> +Consolidate most important and common coding principles for all programming languages. Get acquainted with basic notions of design. All design questions do not require detailed answers. This topic im
> Consolidate

не понятно где нужно закрепить знания о принципах программирования, в голове, или в этом разделе. Может лучше написать изучить принципы?

2021-02-20 09:52 UTC, stanislav-az commented on shared/junior-3/codingAndDesign.md
> +* What are magic numbers and why they are bad?
"magic"  предлагаю поставить в кавычки

2021-02-20 09:52 UTC, stanislav-az commented on shared/junior-3/codingAndDesign.md
> +* What are magic numbers and why they are bad?
И еще предлагаю дописать how bad: bad for understanding/reading code

2021-02-22 03:50 UTC, olegromashin commented on shared/junior-3/codingAndDesign.md
> +* Explain the following practices of design: Iterate, Divide and Conquer, Top-Down and Bottom-Up design approaches.
По-моему слово "практики" здесь больше подходит. Мне кажется принцип - это больше характеристика, а здесь методики.

2021-02-22 04:21 UTC, olegromashin commented on shared/junior-3/codingAndDesign.md
> +* What is Coupling?
Как тебе мой вариант?

2021-02-22 04:22 UTC, olegromashin commented on shared/junior-3/codingAndDesign.md
> +* Is it important to write code with maximum optimization? When you have to start thinking about forcing optimization? Why?
Вопрос про оптимизацию поменял. А про защитное программирование ты бы что добавил? Просто понятие довольно размытое и надо что-то конкретное придумать.

2021-02-22 04:23 UTC, olegromashin commented on shared/junior-3/codingAndDesign.md
> +Consolidate most important and common coding principles for all programming languages. Get acquainted with basic notions of design. All design questions do not require detailed answers. This topic im
Объеденил через союз. А подлежащие здесь "principles" и "notions". Или я ошибаюсь?

2021-02-22 04:23 UTC, olegromashin commented on shared/junior-3/codingAndDesign.md
> +Consolidate most important and common coding principles for all programming languages. Get acquainted with basic notions of design. All design questions do not require detailed answers. This topic im
Поправил, норм?

2021-02-22 04:24 UTC, olegromashin commented on shared/junior-3/codingAndDesign.md
> +* Is it important to write code with maximum optimization? When you have to start thinking about forcing optimization? Why?
Неа, я придумал. Но уже переформулировали вопрос (см. дискашн Кирилла).

2021-02-22 04:25 UTC, olegromashin commented on frontend/junior-3/README.md
> +- [Базовые принципы кодирования и проектирования](../../shared/junior-3/codingAndDesign.md)
Готово. Но я делал также, как на первом мидле сделано у раздела Базовые принципы проектирование :)

2021-02-22 04:26 UTC, olegromashin commented on shared/junior-3/codingAndDesign.md
> +Consolidate most important and common coding principles for all programming languages. Get acquainted with basic notions of design. All design questions do not require detailed answers. This topic im
Переформулировал, что думаешь?

2021-02-22 04:27 UTC, olegromashin commented on shared/junior-3/codingAndDesign.md
> +Consolidate most important and common coding principles for all programming languages. Get acquainted with basic notions of design. All design questions do not require detailed answers. This topic im
https://github.com/fullstack-development/developers-roadmap/pull/282#discussion_r577603677

2021-02-22 04:27 UTC, olegromashin commented on shared/junior-3/codingAndDesign.md
> +Consolidate most important and common coding principles for all programming languages. Get acquainted with basic notions of design. All design questions do not require detailed answers. This topic im
Поправил, норм?

2021-02-22 04:28 UTC, olegromashin commented on shared/junior-3/codingAndDesign.md
> +* What are magic numbers and why they are bad?
Поставил magic в кавычки, но не уверен, что стоит указывать то, что ты написал , т. к. это часть ответа.

2021-02-22 11:26 UTC, kelizarov commented on shared/junior-3/codingAndDesign.md
> +* Is it important to write code with maximum optimization? When you have to start thinking about forcing optimization? Why?
Ну что было и Гудлифа и Макконела: зачем нужно проверять входные данные и насколько нужно защищаться от некорректного ввода.

2021-02-22 11:27 UTC, kelizarov commented on shared/junior-3/codingAndDesign.md
> +* Explain the following practices of design: Iterate, Divide and Conquer, Top-Down and Bottom-Up design approaches.
Ну тогда `design practices`

2021-02-22 11:31 UTC, kelizarov requested changes

2021-02-22 11:31 UTC, kelizarov commented on backend/junior-3/README.md
> +- [Basic principles of coding and design](../../shared/junior-3/basicCodingAndDesignPrinciples.md)
Немного придирка, но название файла и название топика немного отличается :)

2021-02-22 11:31 UTC, kelizarov commented on shared/junior-3/basicCodingAndDesignPrinciples.md
> +Learn the most important and common coding principles for all programming languages and get acquainted with notions of design. When answering on design questions you have to explain your understandin
`explain your understanding` -> `... show that you understand ...`

"Объяснить ваше понимание" даже на русском как-то странно звучит.

2021-02-23 12:11 UTC, aoriens commented on shared/junior-3/basicCodingAndDesignPrinciples.md
> +* Is premature optimaztion harmfull on early stage of development? Explain why?
Опечатка в optimization.
harmfull -> harmful
Можно добавить the перед early stage.
В конце знак вопроса не нужен, ведь это не вопрос.

2021-02-23 12:47 UTC, aoriens commented on shared/junior-3/basicCodingAndDesignPrinciples.md
> +Learn the most important and common coding principles for all programming languages and get acquainted with notions of design. When answering on design questions you have to explain your understandin
When answering on design questions: on -> to.
You have to explain: have to -> need или should. You have to означает "вы вынуждены, вам придется", что не соответствует ситуации.

2021-02-23 12:53 UTC, aoriens commented on shared/junior-3/basicCodingAndDesignPrinciples.md
> +Learn the most important and common coding principles for all programming languages and get acquainted with notions of design. When answering on design questions you have to explain your understandin
> "Объяснить ваше понимание" даже на русском как-то странно звучит.

Если буквальный перевод звучит криво, значит, все ок :).

Я не знаю, как правильно употреблять understanding. Англоязычные люди любят вместо understand употреблять get, realize и др. Есть смутное ощущение, что understand тут бы не употребили.

Понимание можно перевести как comprehension (разумение, постижение) и как interpretation (толкование, точка зрения). Мне больше нравится interpretation.

2021-02-24 01:51 UTC, olgaklimenko approved these changes
Мне нравится, какие вопросы добавлены. Хороший результат долгого обсуждения.

2021-02-24 04:52 UTC, chmnkh commented on shared/junior-3/codingAndDesign.md
> +Consolidate most important and common coding principles for all programming languages. Get acquainted with basic notions of design. All design questions do not require detailed answers. This topic im
Consolidate **что?** principles 
Get acquainted **с чем?** with notions

это не подлежащие, это дополнения

2021-02-24 04:55 UTC, chmnkh commented on frontend/junior-3/README.md
> +- [Базовые принципы кодирования и проектирования](../../shared/junior-3/basicCodingAndDesignPrinciples.md)
у фронтенда так-то кстати вся карта на русском, и тут как по мне спорно, что на английском один топик, но пока хз че с этим делать, напишу, чтобы не забытьб

2021-02-24 04:57 UTC, chmnkh commented on shared/junior-3/basicCodingAndDesignPrinciples.md
> +Learn the most important and common coding principles for all programming languages and get acquainted with notions of design. When answering on design questions you have to explain your understandin
> When answering on design questions you have to explain your understanding and discuss it with interviewers

я вообще не понял, какую смысловую нагрузку это несет, потому что во всех темах ты должен отвечать на вопросы и объяснять что ты понял интервьюерам

2021-02-24 04:59 UTC, chmnkh commented on shared/junior-3/codingAndDesign.md
> +Consolidate most important and common coding principles for all programming languages. Get acquainted with basic notions of design. All design questions do not require detailed answers. This topic im
мне не очень нравится, как-то не совсем понятно звучит
предлагаю написать так: "Более подробно и глубоко принципы дизайна и кодирования будут рассмотрены тут"

2021-02-24 05:01 UTC, chmnkh commented on shared/junior-3/codingAndDesign.md
> +Consolidate most important and common coding principles for all programming languages. Get acquainted with basic notions of design. All design questions do not require detailed answers. This topic im
в новой версии кстати та же фигня

у тебя подлежащее - это The goal, просто оно у тебя тайтлом и ты такой решил его не включать в предложение

надо написать просто The goal is ... ид альше попёр

2021-02-24 05:09 UTC, chmnkh commented on shared/junior-3/codingAndDesign.md
> +Consolidate most important and common coding principles for all programming languages. Get acquainted with basic notions of design. All design questions do not require detailed answers. This topic im
> Ответ все равно должен быть подробный. Он просто не имеет единственно правильного, 100% точного, ожидаемого ответа. 

так здесь именно был смысл в том, чтобы показать собеседующему и собеседуемому, что этот топик - по сути прелюдия для топика на миддле, и что тут не стоит закапываться

то что собесы про такие абстрактные вещи уже сами по себе становятся более абстрактными - это да, но нужно ли это пояснять, или нет - это вопрос отдельный, он немного в стороне стоит от того, что мы хотим здесь сказать

я, кстати, считаю, что не обязательно на этом (на том, что сказал Стас) акцент делать, потому что по сей день проблемы никакой не было, так что решать нам нечего, насколько я могу судить

2021-02-24 05:12 UTC, chmnkh commented on shared/junior-3/codingAndDesign.md
> +Consolidate most important and common coding principles for all programming languages. Get acquainted with basic notions of design. All design questions do not require detailed answers. This topic im
1. я думаю что пункт, поясняющий то, что этот топик - база и прелюдия перед топиком на миддле, надо оставлять, чтобы собеседуемый и собеседующий понимали, что не надо мега-закапываться
2. предложение Стаса не совсем понятно, потому что не понятна проблема, которую Стас этим пытается решить. Для меня это выглядит как предупреждение в духе "внимание, сейчас будет абстрактно", не понимаю, к чему это надо. Но может я мысль не совсем понял правильно.

2021-02-24 08:07 UTC, olegromashin commented on shared/junior-3/basicCodingAndDesignPrinciples.md
> +Learn the most important and common coding principles for all programming languages and get acquainted with notions of design. When answering on design questions you have to explain your understandin
Насколько я знаю "have to" носит оттенок слова "потребуется", но вообще, наверное, надо полностью предложение переформулировать, т. к. мне этот поинт кажется валидным: https://github.com/fullstack-development/developers-roadmap/pull/282#discussion_r581623773

2021-02-26 09:36 UTC, stanislav-az commented on shared/junior-3/codingAndDesign.md
> +Consolidate most important and common coding principles for all programming languages. Get acquainted with basic notions of design. All design questions do not require detailed answers. This topic im
_the_ most important

2021-02-26 09:41 UTC, stanislav-az commented on shared/junior-3/codingAndDesign.md
> +Consolidate most important and common coding principles for all programming languages. Get acquainted with basic notions of design. All design questions do not require detailed answers. This topic im
Я хотел сказать ,что лучше написать вместо "questions do not require _detailed_ answers" -> "questions do not require _conventional formulaic_ answers"

2021-03-01 03:56 UTC, chmnkh commented on shared/junior-3/codingAndDesign.md
> +Consolidate most important and common coding principles for all programming languages. Get acquainted with basic notions of design. All design questions do not require detailed answers. This topic im
> Я хотел сказать ,что лучше написать вместо "questions do not require _detailed_ answers" -> "questions do not require _conventional formulaic_ answers"

можешь плиз пояснить, какую мысль и зачем ты пытаешься донести? не до конца понятно

2021-03-01 09:26 UTC, stanislav-az commented on shared/junior-3/codingAndDesign.md
> +Consolidate most important and common coding principles for all programming languages. Get acquainted with basic notions of design. All design questions do not require detailed answers. This topic im
Бывает что сдающие пытаются найти каноничный ответ, когда выбрать его сложно, поскольку вопрос абстрактный и есть несколько правильных ответов на него, которые либо означают одно и то же по своей сути, либо даже иногда в сообществе мнения какой ответ верен различны. Поэтому хотелось бы предупредить людей, что не нужно здесь пытаться найти единственно правильный ответ, а просто рассказать как в источниках на него отвечают авторы и высказать свое мнение. Если напишем, может у кого-то будет меньше нервов и времени потрачено.

2021-03-04 09:45 UTC, vkpgwt commented on shared/junior-3/codingAndDesign.md
> +* Why it is important to think over requirements in advance? Is it possible to overdo it?
А это имеет значение? Мне кажется, это про любые требования, известные заранее. Кроме бизнес-требований могут быть разные технические соображения, которые нужны только команде, а не заказчику. Они могут удешевлять и упрощать разработку (тесты, простота деплоя, скорость сборки в большом проекте), и чтобы эти требования соблюсти, бывает нужно с самого начала это закладывать в архитектуру.

2021-03-04 09:50 UTC, vkpgwt commented on frontend/junior-3/README.md
> +- [Базовые принципы кодирования и проектирования](../../shared/junior-3/basicCodingAndDesignPrinciples.md)
Я слышал, есть планы переводить всю карту на английский, так что логично делать новые файлы на английском. Может, это и некрасиво, когда остальные топики на русском, но делать два файла на разных языках, имхо, еще хуже.

2021-03-04 10:40 UTC, olegromashin commented on shared/junior-3/codingAndDesign.md
> +* Why it is important to think over requirements in advance? Is it possible to overdo it?
Давай вот здесь обсудим: https://github.com/fullstack-development/developers-roadmap/pull/282#discussion_r577598431

2021-03-04 11:08 UTC, stanislav-az approved these changes

2021-03-04 12:45 UTC, kelizarov commented on shared/junior-3/codingAndDesign.md
> +* Why it is important to think over requirements in advance? Is it possible to overdo it?
Ну вот я бы хотел чтобы про технические требования тут спрашивали. Джуну я думаю не до конца будет еще понятно что есть бизнес-требования и технические, из-за чего ответ на вопрос будет слишком гибким, и тем самым принимающей стороне тоже не ясно какой ответ он будет ждать.

2021-03-04 12:52 UTC, kelizarov commented on shared/junior-3/basicCodingAndDesignPrinciples.md
> +* Is premature optimaztion harmfull on early stage of development? Explain why?
> Premature optimization: я бы удалил premature.

А зачем? Это ж по сути переводится как "преждевременная оптимизация" о чем собственно и вопрос. Ну и то что это носит негативный оттенок, я думаю это нормально. Для сдающего главное не ребус собрать, а попытаться ответить на вопрос при этом привидя аргументы в зацщиту.

2021-03-04 13:28 UTC, vkpgwt commented on shared/junior-3/basicCodingAndDesignPrinciples.md
> +* Is premature optimaztion harmfull on early stage of development? Explain why?
Ну вообще да, смысл в том, чтобы человек рассказал о преждевременной оптимизации, и как ее делать, чтобы она преждевременной не была.
Но что касается вопроса "является ли преждевременная оптимизация вредной" - тут ответ очевиден. Хорошую вещь преждевременной не назовут. Наверное, стоит переформулировать.

2021-03-04 13:55 UTC, olegromashin commented on shared/junior-3/codingAndDesign.md
> +Consolidate most important and common coding principles for all programming languages. Get acquainted with basic notions of design. All design questions do not require detailed answers. This topic im
@chmnkh
Посмотри, плиз

2021-03-04 13:55 UTC, olegromashin commented on shared/junior-3/codingAndDesign.md
> +Consolidate most important and common coding principles for all programming languages. Get acquainted with basic notions of design. All design questions do not require detailed answers. This topic im
Переформулировал

2021-03-04 13:55 UTC, olegromashin commented on shared/junior-3/codingAndDesign.md
> +Consolidate most important and common coding principles for all programming languages. Get acquainted with basic notions of design. All design questions do not require detailed answers. This topic im
Тоже поправил.

2021-03-04 13:56 UTC, olegromashin commented on shared/junior-3/basicCodingAndDesignPrinciples.md
> +Learn the most important and common coding principles for all programming languages and get acquainted with notions of design. When answering on design questions you have to explain your understandin
Переделал полностью.

2021-03-04 13:59 UTC, olegromashin commented on shared/junior-3/basicCodingAndDesignPrinciples.md
> +* Is premature optimaztion harmfull on early stage of development? Explain why?
Исправил ошибки.
The перед early stage решил не добавлять. По-моему не надо.
Слово premature решил удалить. Мне показалось так более корректно.

2021-03-04 13:59 UTC, olegromashin commented on frontend/junior-3/README.md
> +- [Базовые принципы кодирования и проектирования](../../shared/junior-3/basicCodingAndDesignPrinciples.md)
@chmnkh зарезолвим дискашн?

2021-03-04 14:02 UTC, olegromashin commented on shared/junior-3/codingAndDesign.md
> +* Why it is important to think over requirements in advance? Is it possible to overdo it?
Есть идеи как написать?

2021-03-04 15:04 UTC, vkpgwt commented on shared/junior-3/basicCodingAndDesignPrinciples.md
> +* Is premature optimaztion harmfull on early stage of development? Explain why?
Теперь какой-то двусмысленный вопрос получился. Преждевременные оптимизации бывают на любом этапе разработки (так же, как и годные оптимизации). Мне надо было сразу предложить свой вариант:

What is premature optimization and why is it harmful? What should be done in order to make sure that optimization is worth doing? Is any kind of optimization harmful?

Бывают мелкие и хорошие оптимизации, которые код не ухудшают, времени не требуют, одни преимущества.

2021-03-04 15:14 UTC, vkpgwt approved these changes

2021-03-04 16:47 UTC, olegromashin commented on shared/junior-3/basicCodingAndDesignPrinciples.md
> +  * What will happen if exception will not being caught?
Ну как-то тоже не то. Не говорю, что грамматически у меня правильно. Но в твоём варианте получается примерно так: "Что будет если исключение не пойманное?".

2021-03-04 16:52 UTC, olegromashin commented on shared/junior-3/basicCodingAndDesignPrinciples.md
> +* Is premature optimaztion harmfull on early stage of development? Explain why?
Первые два вопроса твоего варианта оставил, третий кажется лишний. Это становится понятно после ответа на первые два вопроса. Как считаешь?

2021-03-04 17:01 UTC, vkpgwt commented on shared/junior-3/basicCodingAndDesignPrinciples.md
> +  * What will happen if exception will not being caught?
Ну да, а разве это не то, что ты хотел?

2021-03-04 17:03 UTC, vkpgwt approved these changes

2021-03-04 17:09 UTC, vkpgwt commented on shared/junior-3/basicCodingAndDesignPrinciples.md
> +* Is premature optimaztion harmfull on early stage of development? Explain why?
Ага, главное написали.

2021-03-04 17:34 UTC, olegromashin commented on shared/junior-3/basicCodingAndDesignPrinciples.md
> +  * What will happen if exception will not being caught?
Ну само предложение неграмотно звучит. Надо спросить, что будет, если исключение "не поймано", а не "не пойманное". Короче нужно краткое причастие, а не обычное)

2021-03-04 18:43 UTC, olegromashin commented on shared/junior-3/codingAndDesign.md
> +* Why it is important to think over requirements in advance? Is it possible to overdo it?
Вообще кстати этот вопрос можно убрать. Это есть у Гудлиффа, который в карте на втором джуне. Ну и да, уровень абстракции слишком высокий.

2021-03-04 19:12 UTC, vkpgwt commented on shared/junior-3/basicCodingAndDesignPrinciples.md
> +  * What will happen if exception will not being caught?
Это условное предложение [first conditional](https://www.perfect-english-grammar.com/first-conditional.html), а может быть и [zero conditional](https://www.perfect-english-grammar.com/zero-conditional.html), но вряд ли. В русском тут два будущих времени, а в английском будет настоящее и будущее, а может и два настоящих. Времена не всегда переводятся буквально.

"Что будет, если исключение не пойманное?" - плохо звучит, потому что так не говорят :).  "Что будет, если исключение *не поймано*" - вот так говорят, нормально же звучит?  "Не будет поймано" - тоже норм, но только для русского языка. В английском положено настоящее время, "не поймано".

"Пойманное" и "поймано" это разные формы одного слова, они сами по себе одинаково переводятся. Примерно как разница между "красная" и "красный" тоже не переводится, потому что она не смысловая, в данном языке так принято говорить и все.

2021-03-04 19:20 UTC, olegromashin commented on shared/junior-3/basicCodingAndDesignPrinciples.md
> +  * What will happen if exception will not being caught?
Убедил)

2021-03-05 03:11 UTC, chmnkh commented on shared/junior-3/codingAndDesign.md
> +Consolidate most important and common coding principles for all programming languages. Get acquainted with basic notions of design. All design questions do not require detailed answers. This topic im
@olegromashin мне короче надоело это обсуждать, если честно, если вы все считаете что нормально без подлежащего - ок, мне проверять не охота :(

2021-03-05 03:13 UTC, chmnkh commented on frontend/junior-3/README.md
> +- [Базовые принципы кодирования и проектирования](../../shared/junior-3/basicCodingAndDesignPrinciples.md)
> Я слышал, есть планы переводить всю карту на английский

эти планы настолько "в потенции" находятся, что я бы не стал о них говорить

это планируется уже пару лет как, когда до этого руки дойдут - неизвестно, так что пока что это вечное todo

2021-03-05 03:14 UTC, chmnkh commented on frontend/junior-3/README.md
> +- [Базовые принципы кодирования и проектирования](../../shared/junior-3/basicCodingAndDesignPrinciples.md)
> @chmnkh зарезолвим дискашн?

давай зарезолвим, я без понятия все равно, че с этим делать

2021-03-05 03:14 UTC, olegromashin commented on shared/junior-3/codingAndDesign.md
> +Consolidate most important and common coding principles for all programming languages. Get acquainted with basic notions of design. All design questions do not require detailed answers. This topic im
@chmnkh Так чего, мы же с тобой голосом обсуждали, что подлежащее можем оставить в заголовке и начать с To...

2021-03-05 03:14 UTC, chmnkh approved these changes

2021-03-05 03:17 UTC, chmnkh commented on shared/junior-3/codingAndDesign.md
> +Consolidate most important and common coding principles for all programming languages. Get acquainted with basic notions of design. All design questions do not require detailed answers. This topic im
нет, мы друг друга не поняли

я говорил, что заголовок - это заголовок, а начало текста - это начало текста

начинать текст с заголовка - так не делается, поэтому отдельно в предложении нужно продублировать `The goal is`, я это имел в виду

2021-03-05 08:41 UTC, olegromashin commented on shared/junior-3/codingAndDesign.md
> +* Why it is important to think over requirements in advance? Is it possible to overdo it?
Убрал.

2021-03-05 08:42 UTC, kelizarov approved these changes

2021-03-05 09:21 UTC, stanislav-az approved these changes

2021-03-05 11:21 UTC, Znack commented on shared/junior-3/basicCodingAndDesignPrinciples.md
> +  * System testing
У нас есть отдельно темы про тестированию, они на фронте правда, но они довольно обобщенно написаны. Можно пока тут оставить, но в будущем надо в shared вынести тестирование с фронта в shared, а отсюда убрать

2021-03-05 11:21 UTC, Znack approved these changes

2021-03-05 11:21 UTC, merged

2021-03-05 11:22 UTC, Znack commented
Ураааа! Поздравляю всех с этой знаменательной датой! 🎉