jun3-extensions-corrections
fullstack-development/developers-roadmap pull request #296
Opened 2021-03-22 10:00 UTC by olegromashin

https://github.com/fullstack-development/developers-roadmap/issues/291
Ещё убрал курс по логике из источников Existential types. Он классный, но всё-таки не совсем относится.

2021-03-22 10:12 UTC, vkpgwt commented on backend/junior-3/haskell.md
> +  * `DerivingVia`
Для `DerivingVia` нужно знать `Coercible`, representations и, возможно, даже type roles. Может, добавить и `Coercible`, либо убрать `DerivingVia`. Не надо стремиться запихнуть все дерайвинги в одно место только потому, что это дерайвинги ).

2021-03-22 10:16 UTC, olegromashin commented on backend/junior-3/haskell.md
> +  * `DerivingVia`
@stanislav-az

2021-03-22 11:11 UTC, vkpgwt commented on backend/junior-3/haskell.md
> -  * Provide example cases on when we can use `ExistentialQuantification` and when we can use `RankNTypes`.
Чем этот вопрос не угодил? Неплохой вопрос на подумать, в чем разница между двумя расширениями. Может быть, стоит уточнить его, но удалять я бы не стал.

2021-03-22 11:14 UTC, olegromashin commented on backend/junior-3/haskell.md
> -  * Provide example cases on when we can use `ExistentialQuantification` and when we can use `RankNTypes`.
Забыл упомянуть про это в шапке. Во первых вопрос стоит до изучения экзистенциальных типов, поэтому на него нельзя ответить. Во вторых в экзистенциальных типах есть свой вопрос: `What are the situations which require using ScopedTypeVariables, ExistentialQuantification, RankNTypes? Compare the use cases of these extensions.`

2021-03-22 11:17 UTC, olegromashin commented on backend/junior-3/haskell.md
> +#### Resources
Эти экстеншены будут пачкой сдаваться, поэтому к ним один подзаголовок источников. Просто чтобы не дробить сильно. На первом джуне ресурсы почти везде также, по-моему достаточно опрятно.

2021-03-22 11:27 UTC, vkpgwt commented on backend/junior-3/haskell.md
> +#### Resources
Я не то написал. Смотри, краткая схема текста:

- заголовок Resources и источник по wildcards
- Через строку: вопрос по TypeOperators и т.п.

Получается, вопрос по TypeOperators логически находится под заголовком Resources. Но ведь это не ресурс, это вопрос. После заголовка Resources с источниками должен идти новый заголовок с темой, вроде Extensions, где идет новая серия вопросов.

2021-03-22 11:29 UTC, vkpgwt commented on backend/junior-3/haskell.md
> -  * Provide example cases on when we can use `ExistentialQuantification` and when we can use `RankNTypes`.
+1, не увидел сначала.

2021-03-22 12:12 UTC, olegromashin commented on backend/junior-3/haskell.md
> +#### Resources
ага, понял о чём ты)
поправил, норм?

2021-03-22 12:32 UTC, vkpgwt commented on backend/junior-3/haskell.md
> +#### Resources
По правилам оформления заголовок Resources должен быть на два уровня ниже заголовка с топиком.

Можно удалить заголовок GHC Extensions и повысить заголовки топиков под ним до уровня 3. Тогда заголовки Resources должны быть на уровне 5.

2021-03-22 14:06 UTC, stanislav-az commented on backend/junior-3/haskell.md
> +  * `DerivingVia`
Создал связанный ишью https://github.com/fullstack-development/developers-roadmap/issues/298 . Но я думаю что тут не нужно подробно знать что такое `Coercible` для того чтобы понять зачем нужен `DerivingVia`, поэтому в ишью написал два предложения, одно из базовых вопросов, другое для получения углубленных знаний по теме.

2021-03-22 14:41 UTC, stanislav-az requested changes

2021-03-22 14:41 UTC, stanislav-az commented on backend/middle-1/haskell.md
> +* How Generic programming can be improved with this `ConstraintKinds` extension enabled?
А к чему тут слово this?

2021-03-22 14:41 UTC, stanislav-az commented on backend/middle-1/haskell.md
>  #### Generics resources
Сюда тогда надо перенести ресурс в котором обсуждалось generic programming в контексте `ConstraintKinds`

2021-03-22 14:41 UTC, stanislav-az commented on backend/junior-3/haskell.md
>  ### GHC extensions
А почему теперь некоторые экстеншены не являются вложенными в этот топик?

2021-03-22 14:43 UTC, stanislav-az commented on backend/junior-3/haskell.md
>  ### GHC extensions
Тут еще удались его предлагалось, но куда вынести тогда экстеншены по которым нет списка вопросов, а они просто упоминаются?

2021-03-23 04:01 UTC, olegromashin commented on backend/junior-3/haskell.md
> +  * `DerivingVia`
Тогда оставляем.

2021-03-23 04:07 UTC, olegromashin commented on backend/junior-3/haskell.md
> +#### Resources
Я думаю надо оставить как на всём уровне сейчас есть и сделать отдельное ишью на это. Потому что по правилам надо не только этот уровень переделывать.

2021-03-23 04:10 UTC, olegromashin commented on backend/junior-3/haskell.md
>  ### GHC extensions
> А почему теперь некоторые экстеншены не являются вложенными в этот топик?

Что ты имеешь  в виду? Все экстеншены являются подразделами GHC excensions.

2021-03-23 04:15 UTC, olegromashin commented on backend/middle-1/haskell.md
> +* How Generic programming can be improved with this `ConstraintKinds` extension enabled?
Невнимательно переформулировал старый вопрос)

2021-03-23 05:41 UTC, Znack commented on backend/junior-3/haskell.md
> +#### Resources
Я больше сторонник того чтобы такие вещи рефакторить понемногу прямо в ПРах, которые связанны с темой. То есть тут изменяете топик про экстеншены, и тут же сразу рефакторите оформление — так со временем единообразие везде появится. А отдельно ждать пока кто-то весь грейд прорабоатет мы можем очень долго :)

2021-03-23 05:55 UTC, olegromashin commented on backend/junior-3/haskell.md
> +#### Resources
https://github.com/fullstack-development/developers-roadmap/pull/294#issuecomment-802703429
Оппа :))

2021-03-23 06:01 UTC, olegromashin commented on backend/junior-3/haskell.md
> +#### Resources
Посмотрите кто-то плиз, что всё норм.

2021-03-23 06:03 UTC, olegromashin commented on backend/junior-3/haskell.md
>  ### GHC extensions
Сейчас неактуально, сделал как Антон здесь предлагал: https://github.com/fullstack-development/developers-roadmap/pull/296#discussion_r598673608

2021-03-23 07:16 UTC, vkpgwt requested changes

2021-03-23 07:16 UTC, vkpgwt commented on backend/junior-3/haskell.md
> +* RecordWildCards
Одинокий элемент списка, может его выпилить и поднять дочерние элементы на уровень вверх? В других местах аналогично:

- источники по тайпфемили
- источники по Higher ranked types (только к источнику GHC Docs надо бы дописать, что это дока именно по HRT, а то в этом разделе спрашивается еще про scoped type variables).

2021-03-23 07:17 UTC, vkpgwt approved these changes

2021-03-23 07:47 UTC, olegromashin commented on backend/junior-3/haskell.md
> +* RecordWildCards
Тайп фемелис поправил. У остальных сделано также как и везде: в пачке, которая сдаётся вместе и имеет один подраздел ресурсов, указывается так к какой теме относится источник.

2021-03-23 08:05 UTC, vkpgwt commented on backend/junior-3/haskell.md
> +* RecordWildCards
В названии ресурса по wildcards уже есть слово wildcards - не перепутаешь. Я бы оставил двухуровневый список только в том случае, если есть хотя бы два ресурса по wildcards и хотя бы один ресурс по другой теме - тогда получилась бы наглядная группировка. А сейчас это часть структуры документа, которая ничего не структурирует, не улучшает навигацию. Но я не настаиваю.

2021-03-23 08:11 UTC, vkpgwt approved these changes

2021-03-23 08:11 UTC, vkpgwt approved these changes

2021-03-23 09:06 UTC, olegromashin commented on backend/junior-3/haskell.md
> +* RecordWildCards
Ну меня вообще тоже любой вариант устроит. Я просто с расчётом на то, что что-то добавиться может и структуру не поменяют в итоге.

2021-03-23 14:00 UTC, olgaklimenko approved these changes

2021-03-26 09:03 UTC, stanislav-az approved these changes

2021-03-26 11:19 UTC, Znack approved these changes

2021-03-26 11:19 UTC, merged