fe-mid1/async: update questions
fullstack-development/developers-roadmap pull request #305
Opened 2021-04-05 04:44 UTC by chmnkh

fixes #301 

Выпилил вопросы, о которых писал @iatsdotfatr. Еще от себя вопросы добавил, которые всегда, на мой взгляд (и по моему опыту собесов) подразумевались, но не были явно обозначены никак.

2021-04-05 06:58 UTC, sk1e requested changes

2021-04-05 06:58 UTC, sk1e commented on frontend/middle-1/async.md
> +    * Какие в серверной разработке есть альтернативы? Какие у них преимущества и недостатки относительно асинхронного подхода?
Альтернатива ивент лупу тогда уж, это всё вариации асинхронности а не альтернатива

2021-04-08 03:58 UTC, Znack approved these changes
С Серегой согласен, а так аппрув.

2021-04-08 06:11 UTC, iatsdotfatr approved these changes

2021-04-15 04:48 UTC, chmnkh commented
@sk1e резольвед

2021-04-15 04:50 UTC, sk1e approved these changes

2021-04-15 04:56 UTC, merged