Упрощение jun3 Haskell
fullstack-development/developers-roadmap pull request #308
Opened 2021-04-07 03:15 UTC by olgaklimenko

Задача: https://github.com/fullstack-development/developers-roadmap/issues/287

Решили не создавать 4го джуна, а перенести немного на 2го джуна и немного на миддла.

 **На 2го джуна:**

- Deriving, RecordWildCards extensions
- Validation Applicative
- Monad (вопросы про runIO и трансформер IO) + дополнить вопросами про ST Monad (это в отдельной таске)

**на 1го миддла:**

- PolyKinds
- ConstraintKinds
- GHCi Debugger

+ в этом ПР поправила разметку Jun2, сделала её такой же,  как в Jun3 и Mid1.

2021-04-07 03:17 UTC, olgaklimenko commented on backend/junior-2/haskell.md
> +
лишняя строка

2021-04-07 03:17 UTC, olgaklimenko commented on backend/junior-2/haskell.md
> +
лишняя строка

2021-04-07 04:51 UTC, kelizarov approved these changes

2021-04-07 05:36 UTC, Znack approved these changes

2021-04-07 06:22 UTC, olgaklimenko commented on backend/junior-3/haskell.md
> +### TypeOperators and type classes extensions:
вернуть апостроф

2021-04-07 07:11 UTC, antonkalinin-ml requested changes

2021-04-07 07:11 UTC, antonkalinin-ml commented on backend/junior-2/haskell.md
> +  * `DerivingVia`
Может, уберем DerivingVia обратно на jun-3? Но я не уверен.

Здесь много мелких экстеншенов, которые сдающему надо запомнить в один момент. Большинство из них он видит впервые в жизни и они пригодятся ему нескоро. Читать про них и пытаться запомнить это все несколько утомительно. Я бы их разделил на такие категории:

- часто нужны: GeneralizedNewtypeDeriving
- нечасто нужны, но простые. Полезно знать, что они есть в природе, не углубляясь в детали: DeriveAnyClass, DerivingStrategies, Derive(Functor|Foldable|Traversable), StandaloneDeriving
- DerivingVia

DerivingVia для меня наиболее запутанный экстеншен, и он редко используется.

2021-04-07 07:18 UTC, olgaklimenko commented on backend/junior-2/haskell.md
> +#### Modules resources
Справедливо. Я просто увидела что есть просто ресурсы и есть ресурсы по теме, и выбрала с темой. Поправлю)

2021-04-07 07:36 UTC, stanislav-az commented on backend/junior-3/haskell.md
>  * `Debug.Trace`
думаю лучше просто после `runIO` написать эти вопросы, не стал бы раздел удалять, это все-таки по смыслу разделено, и так выглядит логичнее, вопросы здесь про дебагинг, не про IO, ну да, они связаны, но это не одна тема

2021-04-07 07:54 UTC, stanislav-az approved these changes

2021-04-07 12:52 UTC, olgaklimenko commented on backend/junior-2/haskell.md
> +  * `DerivingVia`
Сейчас, кажется, куда DerivingVia не двигай, всё равно запутанно.

У нас есть ишью про добавление вопросов про `coerce`, но пока не понятно куда, можно будет `DerivingVia` потом положить на тот же уровень. https://github.com/fullstack-development/developers-roadmap/issues/298

2021-04-07 12:54 UTC, olgaklimenko commented on backend/junior-3/haskell.md
>  * `Debug.Trace`
Ну тогда если оставлять отдельным разделом, можно и не переносить наверно) пусть будет маленький раздел, который можно сдать с другими вопросами за один созвон, не вижу в этом ничего плохого.

2021-04-07 13:40 UTC, antonkalinin-ml approved these changes

2021-04-08 03:38 UTC, olegromashin approved these changes

2021-04-08 03:43 UTC, merged