Shared/mid-2/algorithms data structures 2
fullstack-development/developers-roadmap pull request #351
Opened 2022-02-25 09:42 UTC by stanislav-az

Добавлены новые вопросы и источники, а также практические задания. Тема перенесена в shared.

2022-02-25 09:46 UTC, sk1e requested changes

2022-02-25 09:46 UTC, sk1e commented on shared/middle/algorithmsAndDataStructures.md
> +* [Курс "Основы теории графов". Разделы 1-2](https://stepik.org/126)
надо добавить в вопросы что упражнения нужно сделать и показать результат

2022-02-25 09:53 UTC, stanislav-az commented on shared/middle/algorithmsAndDataStructures.md
> +* [Курс "Основы теории графов". Разделы 1-2](https://stepik.org/126)
я добавил внизу список упражнений, к алгоритмам

2022-02-25 09:55 UTC, sk1e approved these changes

2022-02-25 09:55 UTC, sk1e commented on shared/middle/algorithmsAndDataStructures.md
> +* [Курс "Основы теории графов". Разделы 1-2](https://stepik.org/126)
а, точняк

2022-02-28 09:59 UTC, iatsdotfatr commented
Через гитхаб нормально зашел. Возможно, надо как-то продублировать в практических заданиях ссылку на курс, чтобы было понятно, что задания лучше выполнять в рамках прохождения курса, иначе не так просто в них разобраться.

2022-03-05 14:08 UTC, Znack commented
на меня не ориентируйтесь плиз, тут лучше вам самим отревьюить и вмержить, как посчитаете нужным :)

2022-03-09 07:26 UTC, iatsdotfatr approved these changes

2022-03-09 08:30 UTC, merged