Creating python roadmap
fullstack-development/developers-roadmap pull request #377
Opened 2022-12-01 08:15 UTC by alagunoff

2022-12-08 15:21 UTC, alagunoff commented on backend/python/junior-1/django.md
> +- Is Django on MVC?
*Is Django based on MVC?

2022-12-08 15:21 UTC, alagunoff commented on backend/python/junior-1/django.md
> +- Describe main modules django app. What purpose of each?
- По правилам, предпочтение следует отдавать вопросительной форме, а не утвердительной
- А что конкретно имеется ввиду под модулями приложения? Models, Views и тд?

2022-12-15 06:47 UTC, stanislav-az commented
Хотелось бы еще вопросы про виртуальные окружения: что такое, для чего, как использовать. Разница между venv, virtualenv, pipenv, conda, poetry

2022-12-15 06:54 UTC, stanislav-az commented
И еще вопросы про линтеры, и как проверять что сходятся типы в аннотациях

2022-12-19 06:41 UTC, alagunoff commented
> Хотелось бы еще вопросы про виртуальные окружения: что такое, для чего, как использовать. Разница между venv, virtualenv, pipenv, conda, poetry

С первой частью согласен, можно добавить в первого джуна по питону. По второй не очень понял, это разные python модули, которые делают разные вещи)

2022-12-19 06:42 UTC, alagunoff commented
> И еще вопросы про линтеры, и как проверять что сходятся типы в аннотациях

"и как проверять что сходятся типы в аннотациях"
Что ты тут услышать хочешь?

2022-12-19 06:51 UTC, alagunoff commented on backend/python/junior-1/django.md
> +  - What are null, blank, primary_key, help_text, default, unique attributes of a field used for?
Может быть arguments, а не attributes?

2022-12-19 06:51 UTC, alagunoff commented on backend/python/junior-1/django.md
> +  - What are on_delete, verbose_name and related_name used for in relation field?
- Заключи on_delete и т.д. в ``
- Также, нужно добавить уточнение, что это аргументы

2022-12-19 06:51 UTC, alagunoff commented on backend/python/junior-1/django.md
> +  - What are migrations? how to create and apply migrations?
Думаю стоит разделить на несколько вопросов

2022-12-19 06:51 UTC, alagunoff commented on backend/python/junior-1/django.md
> +  - What is the difference between path, include, reverse?
``

2022-12-19 06:51 UTC, alagunoff commented on backend/python/junior-1/django.md
> +  - How works validation of model form?
* How does validation of a model form work?

2022-12-19 06:53 UTC, stanislav-az commented
> это разные python модули, которые делают разные вещи

Разве все эти инструменты (venv, virtualenv, pipenv, conda, poetry) не для создания виртуальных окружений? Я когда гуглил про это натыкался на все эти названия, но в итоге использую venv, ты вроде мне его тоже рекомендовал.

2022-12-19 06:55 UTC, alagunoff commented
@dashkevi4mike И нужно добавить ресурсы для изучения всех подтем

2022-12-19 06:56 UTC, alagunoff commented
> > это разные python модули, которые делают разные вещи
> 
> Разве все эти инструменты (venv, virtualenv, pipenv, conda, poetry) не для создания виртуальных окружений? Я когда гуглил про это натыкался на все эти названия, но в итоге использую venv, ты вроде мне его тоже рекомендовал.

Я про venv только слышал и да, он для создания виртуального окружения используется. conda и poetry это вроде как альтернатива pip

2022-12-19 06:58 UTC, stanislav-az commented
> Что ты тут услышать хочешь?

Ну мне посоветовали проверять типы из аннотаций с помощью тайп чекера https://github.com/microsoft/pyright . Он включается в vs code если включить расширение pylance (ms-python.vscode-pylance). Это вместо этапа компиляции, к которому я привык) Но вообще, иногда это мешает: не все соблюдают конвенции с аннотациями типов.

2022-12-19 07:02 UTC, stanislav-az commented
> Я про venv только слышал и да, он для создания виртуального окружения используется. conda и poetry это вроде как альтернатива pip

Наверное, лучше спросить тогда просто про venv, так как он рекомендован в офицальной доке питона. Самый классный ответ про разницу этих инструментов я находил [тут](https://stackoverflow.com/a/65854168/8375337).

2022-12-20 06:42 UTC, alagunoff commented
> > Что ты тут услышать хочешь?
> 
> Ну мне посоветовали проверять типы из аннотаций с помощью тайп чекера https://github.com/microsoft/pyright . Он включается в vs code если включить расширение pylance (ms-python.vscode-pylance). Это вместо этапа компиляции, к которому я привык) Но вообще, иногда это мешает: не все соблюдают конвенции с аннотациями типов.

Мне кажется это не совсем на первого джуна подходит. Ну т.е. человек будет уметь пользоваться языком, но ему не обязательно знать, что можно подключить проверку типов для питона. Я хоть и не стоял на боевом проекте по питону еще, но @dashkevi4mike говорит, что у него на текущем проекте не используется type checker. Поэтому это конечно хорошо его подключить, но не прям уж обязательно

2022-12-20 06:50 UTC, alagunoff commented
@stanislav-az added questions about virtual environment

2022-12-20 11:50 UTC, stanislav-az commented
Еще надо бы добавить вопросы про модульную систему и пакеты: как организовать иерархию модулей в пакете, для чего файл `__init__.py`, относительные обращения (`.mod`, `..mod`), импорты (`from`, `as`, `*`)

2022-12-21 06:39 UTC, alagunoff commented
> Еще надо бы добавить вопросы про модульную систему и пакеты: как организовать иерархию модулей в пакете, для чего файл `__init__.py`, относительные обращения (`.mod`, `..mod`), импорты (`from`, `as`, `*`)

Есть вводный вопрос же про то, что такое модули и пакеты

"как организовать иерархию модулей в пакете"
Это вопрос уже не на первого джуна. Ему ненужно знать как правильно организовать, ему нужно уметь в питоне, когда его подключат на проект. В проекте уже будет заложена архитектура.

2022-12-21 09:22 UTC, stanislav-az approved these changes

2022-12-26 05:26 UTC, kelizarov requested changes

2022-12-26 05:26 UTC, kelizarov commented on backend/python/junior-1/django.md
> +- Why business logic in view layer is bad?
Не рано ли тут у джунов спрашивать про бизнесс логику? Думаю это можно на уровень выше поднять там 2 или 3 и сделать отдельный топик вопросов про бизнесс логику. Просто это как раз после книги должно помочь.

2022-12-27 03:56 UTC, olgaklimenko commented
> > > Что ты тут услышать хочешь?
> > 
> > 
> > Ну мне посоветовали проверять типы из аннотаций с помощью тайп чекера https://github.com/microsoft/pyright . Он включается в vs code если включить расширение pylance (ms-python.vscode-pylance). Это вместо этапа компиляции, к которому я привык) Но вообще, иногда это мешает: не все соблюдают конвенции с аннотациями типов.
> 
> Мне кажется это не совсем на первого джуна подходит. Ну т.е. человек будет уметь пользоваться языком, но ему не обязательно знать, что можно подключить проверку типов для питона. Я хоть и не стоял на боевом проекте по питону еще, но @dashkevi4mike говорит, что у него на текущем проекте не используется type checker. Поэтому это конечно хорошо его подключить, но не прям уж обязательно

Я за то, чтобы сразу учить писать аннотации к типам и проверять их. Особенно если мы хотим брать проекты под ключ, писать бэкенд с нуля - лучше сразу это изучить и пользоваться всей команде, начиная с 1го джуна. Если мы идём на поддержку чужого кода, где нет аннотаций и тайпчека - можно просто добавлять его потихоньку в свой код (у тайпчекера должна есть опция не требовать аннотации, но если они есть - проверять).

2022-12-27 04:32 UTC, olgaklimenko requested changes

2022-12-27 04:32 UTC, olgaklimenko commented on backend/python/junior-1/python.md
> +  - What is it?
Это вкусовщина, но мне прям не заходит такой формат вопросов, где вместо названия объекта вопроса стоит it, выглядит несерьезно. Я бы исправила тут и еще в других вопросах ниже на такое:
- What is Python?
- What is Python used for?
- What is variable?
и т.д.

2022-12-27 04:32 UTC, olgaklimenko commented on backend/python/junior-1/python.md
> +  - What are it's pros?
А плюсы и минусы по сравнению с чем надо рассматривать? Мб стоит указать точно с чем сравнивать?

2022-12-27 04:32 UTC, olgaklimenko commented on backend/python/junior-1/django.md
> +- What are null, blank, primary_key, help_text, default, unique attributes of a field used for?
Оформление: `null`, `blank`, `primary_key`, `help_text`, `default`, `unique`

2022-12-27 04:32 UTC, olgaklimenko commented on backend/python/junior-1/django.md
> +- Which relations between models are exist?
Лучше спросить, как в вопросе выше (где мы сами перечисляем аттрибуты) про конкретные релейшены.

2022-12-27 04:32 UTC, olgaklimenko commented on backend/python/junior-1/django.md
> +- What are on_delete, verbose_name and related_name used for in relation field?
Оформление: 
- What are `on_delete`, `verbose_name` and `related_name` used for in relation field?

2022-12-27 04:32 UTC, olgaklimenko commented on backend/python/junior-1/django.md
> +- Which methods and operators exist for filter model queries?
Самим перечислить и спросить про каждый

2022-12-27 04:32 UTC, olgaklimenko commented on backend/python/junior-1/django.md
> +- What is the difference between path, include, reverse?
Оформление:
- What is the difference between `path`, `include`, `reverse`?

2022-12-27 04:32 UTC, olgaklimenko commented on backend/python/junior-1/python.md
> +  - What is it?
Вот этот вопрос слишком глубокий для джуна-1. Надо обозначить что конкретно мы хотим услышать - чтобы джун-1 рассказал про ООП, интерпритатор, динамическую типизацию и т.д - и при этом понимал про что он рассказывает, или просто познакомился с терминами, которые описывают язык? Или чтобы он просто сказал что это язык программирования и используется для того и этого? 

Я бы из всех вопросов про `Python` оставила бы "Для чего он может использоваться" и про плюсы минусы в сравнении с другими языками, если есть опыт программирования на чём-то ещё. Про особенности питона можно потом на уровнях выше подробнее спросить.

2022-12-27 10:10 UTC, alagunoff commented on backend/python/junior-1/python.md
> +  - What is it?
А мне наоборот такой стиль больше по душе. У нас есть тема вопроса `Python` далее идут вопросы, которые по этой теме и не нужно каждый раз писать `What is Python?`, `What is Python used for?`, `python`, `python` и т.д.

2022-12-27 10:12 UTC, alagunoff commented on backend/python/junior-1/python.md
> +  - What is it?
У нас и такой стиль и такой в написании используется. Если уж исправлять, то исправлять наверное везде, ну или голосовать, чтобы большинством прийти к какому-то решению

2022-12-27 10:19 UTC, alagunoff commented
> > > > Что ты тут услышать хочешь?
> > > 
> > > 
> > > Ну мне посоветовали проверять типы из аннотаций с помощью тайп чекера https://github.com/microsoft/pyright . Он включается в vs code если включить расширение pylance (ms-python.vscode-pylance). Это вместо этапа компиляции, к которому я привык) Но вообще, иногда это мешает: не все соблюдают конвенции с аннотациями типов.
> > 
> > 
> > Мне кажется это не совсем на первого джуна подходит. Ну т.е. человек будет уметь пользоваться языком, но ему не обязательно знать, что можно подключить проверку типов для питона. Я хоть и не стоял на боевом проекте по питону еще, но @dashkevi4mike говорит, что у него на текущем проекте не используется type checker. Поэтому это конечно хорошо его подключить, но не прям уж обязательно
> 
> Я за то, чтобы сразу учить писать аннотации к типам и проверять их. Особенно если мы хотим брать проекты под ключ, писать бэкенд с нуля - лучше сразу это изучить и пользоваться всей команде, начиная с 1го джуна. Если мы идём на поддержку чужого кода, где нет аннотаций и тайпчека - можно просто добавлять его потихоньку в свой код (у тайпчекера есть опция не требовать аннотации, но если они есть - проверять).

Так я тоже за это, безусловно. Что мы тут конкретно хотим, добавить пулл вопросов о том что это такое, как использовать и тд? Мне кажется, когда джуна подключат на проект, он сам там освоится в этом всем. Для каждого аспекта языка если добавлять вопросы, то топик разрастется очень сильно

2022-12-27 10:21 UTC, alagunoff commented on backend/python/junior-1/python.md
> +  - What is it?
"Или чтобы он просто сказал что это язык программирования и используется для того и этого?"
Именно это и хотел бы я услышать в ответ на этот вопрос. Какие-то уточняющие моменты, мне кажется, тут не подразумеваются и будут само собой добавлены в уровни выше

2022-12-27 10:26 UTC, alagunoff commented on backend/python/junior-1/python.md
> +  - What are it's pros?
Хм, согласен. Не подумал о том, что человек может взяться за питон как за первый яп и тут будет сложно ответить. Ну можно вообще выпилить про плюсы и минусы тогда и оставить 2 вопроса, чтобы человек понимал просто с чем имеет дело и для чего нужен инструмент?

2022-12-28 02:45 UTC, olgaklimenko commented on backend/python/junior-1/python.md
> +  - What is it?
Ок, пусть остаётся.

2022-12-28 02:49 UTC, olgaklimenko commented
> > > > > Что ты тут услышать хочешь?
> > > > 
> > > > 
> > > > Ну мне посоветовали проверять типы из аннотаций с помощью тайп чекера https://github.com/microsoft/pyright . Он включается в vs code если включить расширение pylance (ms-python.vscode-pylance). Это вместо этапа компиляции, к которому я привык) Но вообще, иногда это мешает: не все соблюдают конвенции с аннотациями типов.
> > > 
> > > 
> > > Мне кажется это не совсем на первого джуна подходит. Ну т.е. человек будет уметь пользоваться языком, но ему не обязательно знать, что можно подключить проверку типов для питона. Я хоть и не стоял на боевом проекте по питону еще, но @dashkevi4mike говорит, что у него на текущем проекте не используется type checker. Поэтому это конечно хорошо его подключить, но не прям уж обязательно
> > 
> > 
> > Я за то, чтобы сразу учить писать аннотации к типам и проверять их. Особенно если мы хотим брать проекты под ключ, писать бэкенд с нуля - лучше сразу это изучить и пользоваться всей команде, начиная с 1го джуна. Если мы идём на поддержку чужого кода, где нет аннотаций и тайпчека - можно просто добавлять его потихоньку в свой код (у тайпчекера есть опция не требовать аннотации, но если они есть - проверять).
> 
> Так я тоже за это, безусловно. Что мы тут конкретно хотим, добавить пулл вопросов о том что это такое, как использовать и тд? Мне кажется, когда джуна подключат на проект, он сам там освоится в этом всем. Для каждого аспекта языка если добавлять вопросы, то топик разрастется очень сильно. Как по мне, это больше к best practices относится, нежели чем к теме

Мне наоборот кажется, что это не к best practices относится, а к must have. Также как и `venv` - ты можешь его не настраивать и использовать глобальное окружение, но лучше сразу научиться разделять окружения и понимать почему это нужно, чем потом узнать это на проекте. При этом на 1 джуне как раз происходит изучение основных типов, почему бы сразу не чекнуть типы функций, в которых ты их используешь.

2022-12-28 02:53 UTC, olgaklimenko commented on backend/python/junior-1/python.md
> +  - What are it's pros?
Можно оставить как опциональный вопрос,
If you have experience with other programming languages, what are pros and cons of Python in comparison with them?
Или удалить, да.

2022-12-28 06:38 UTC, alagunoff commented on backend/python/junior-1/python.md
> +  - What are it's pros?
Я бы лучше этот вопрос занес на 2 джуна в обязательные, чтобы человек разобрался уже поглубже в языке, поэтому - удалил

2022-12-28 06:39 UTC, alagunoff commented
> > > > > > Что ты тут услышать хочешь?
> > > > > 
> > > > > 
> > > > > Ну мне посоветовали проверять типы из аннотаций с помощью тайп чекера https://github.com/microsoft/pyright . Он включается в vs code если включить расширение pylance (ms-python.vscode-pylance). Это вместо этапа компиляции, к которому я привык) Но вообще, иногда это мешает: не все соблюдают конвенции с аннотациями типов.
> > > > 
> > > > 
> > > > Мне кажется это не совсем на первого джуна подходит. Ну т.е. человек будет уметь пользоваться языком, но ему не обязательно знать, что можно подключить проверку типов для питона. Я хоть и не стоял на боевом проекте по питону еще, но @dashkevi4mike говорит, что у него на текущем проекте не используется type checker. Поэтому это конечно хорошо его подключить, но не прям уж обязательно
> > > 
> > > 
> > > Я за то, чтобы сразу учить писать аннотации к типам и проверять их. Особенно если мы хотим брать проекты под ключ, писать бэкенд с нуля - лучше сразу это изучить и пользоваться всей команде, начиная с 1го джуна. Если мы идём на поддержку чужого кода, где нет аннотаций и тайпчека - можно просто добавлять его потихоньку в свой код (у тайпчекера есть опция не требовать аннотации, но если они есть - проверять).
> > 
> > 
> > Так я тоже за это, безусловно. Что мы тут конкретно хотим, добавить пулл вопросов о том что это такое, как использовать и тд? Мне кажется, когда джуна подключат на проект, он сам там освоится в этом всем. Для каждого аспекта языка если добавлять вопросы, то топик разрастется очень сильно. Как по мне, это больше к best practices относится, нежели чем к теме
> 
> Мне наоборот кажется, что это не к best practices относится, а к must have. Также как и `venv` - ты можешь его не настраивать и использовать глобальное окружение, но лучше сразу научиться разделять окружения и понимать почему это нужно, чем потом узнать это на проекте. При этом на 1 джуне как раз происходит изучение основных типов, почему бы сразу не чекнуть типы функций, в которых ты их используешь.

Ну согласен, ок. Может сама сделаешь коммит, а я посмотрю и поправлю, чтобы духу темы соответствовало? Я просто не очень понимаю как это лучше сформулировать

2022-12-29 11:05 UTC, olgaklimenko commented
Добавила топик про аннотацию типов.

2022-12-30 06:56 UTC, alagunoff commented
@olgaklimenko
Круто, спасибо за вклад в пр!)
Чуть поправил, а именно:
- Убрал прослойку questions в list of contents, тк у нас заголовок темы и есть "Вопросы", а содержание как раз таки темы - basics и т.д.
- Вынес вопрос про типизацию функции в отдельную задачу в "Practice"
- Убрал вопросы про `mypy`, тк это ну больно уж узкая тема. Я его вообще не использую, к примеру, в vscode есть расширение pylance, которое pyright под капотом использует. Так что, я думаю, тут уже дело вкуса, главное, чтобы человек знал о type annotations и умел их использовать себе во благо)
+ разнес вопросы по модулям и пакетам, виртуальной среде в отдельные секции.
Ждем пока @dashkevi4mike поправит джангу)

2023-03-28 08:09 UTC, kelizarov approved these changes

2023-03-28 08:09 UTC, kelizarov commented on backend/python/junior-1/django.md
> +- [Django documentation](https://docs.djangoproject.com/)
Можно ссылку добавить конкретные в доку, чтобы не искать потом каждый раз. А то общая ссылка повторяется несколько раз для разных модулей.

2023-06-22 02:38 UTC, olgaklimenko commented
@alagunoff @dashkevi4mike Давайте мёржить?

2023-06-23 05:19 UTC, dashkevi4mike approved these changes

2023-06-23 05:19 UTC, merged