backend: added metrics topic
fullstack-development/developers-roadmap pull request #381
Opened 2023-08-10 09:05 UTC by olegromashin

Топик по метрикам после которого разработчик должен уметь оперировать понятиями, встречающимися при настройке метрик, уметь пользоваться Prometheus и Grafana, настраивать их и экспортировать кастомные метрики из своего приложения.

Мне не довелось долго работать с этими инструментами, поэтому если я упустил какие-то важные вещи, то, пожалуйста, дополните :)

2023-08-11 04:47 UTC, pavelzarubin commented on backend/optional/metrics.md
> +* What is quantile? Basic understanding is enough.
может добавить статью про квантили?
https://ru.wikipedia.org/wiki/%D0%9A%D0%B2%D0%B0%D0%BD%D1%82%D0%B8%D0%BB%D1%8C

2023-08-15 06:32 UTC, pavelzarubin approved these changes

2023-08-15 08:16 UTC, kelizarov approved these changes

2023-08-22 06:38 UTC, stanislav-az requested changes

2023-08-22 06:38 UTC, stanislav-az commented on backend/optional/metrics.md
> +# Metrics: Prometheus and Grafana
Добавишь еще ссылку в [оглавление](https://github.com/fullstack-development/developers-roadmap/blob/master/backend/README.md) раздела?

2023-08-25 05:52 UTC, stanislav-az approved these changes

2023-08-25 05:52 UTC, merged