Python junior-2
fullstack-development/developers-roadmap pull request #383
Opened 2023-10-05 05:29 UTC by olgaklimenko

2023-10-23 14:07 UTC, pavelzarubin commented on backend/python/junior-2/python.md
> +- What is a `__str__` method?
Можно и вопрос про `__repr__` добавить.

2023-10-24 01:51 UTC, olgaklimenko commented on backend/python/junior-2/python.md
> +- What is a `__str__` method?
Спасибо, добавила)

2023-10-26 09:55 UTC, kelizarov requested changes

2023-10-26 09:55 UTC, kelizarov commented on backend/python/junior-2/python.md
> +- How to create a custom iterator?
Дублируется вопрос с `How to create iterator? `

2023-10-26 09:55 UTC, kelizarov commented on backend/python/junior-2/python.md
> +## Generators
Добавить информацию о `sequence` и сравнить с iterable

2023-10-26 09:55 UTC, kelizarov commented on backend/python/junior-2/python.md
> +- Is it possible to call decorated function without running code from wrapper?
`decorated` -> `decorator`

2023-10-26 09:55 UTC, kelizarov commented on backend/python/junior-2/python.md
> +- How to decorate function if it waits arguments?
`waits` -> `accepts`

2023-12-15 12:18 UTC, kelizarov approved these changes

2023-12-21 05:54 UTC, dashkevi4mike approved these changes

2023-12-21 07:16 UTC, stanislav-az approved these changes

2023-12-21 07:16 UTC, merged