Improve mid1 async questions
fullstack-development/developers-roadmap pull request #396
Opened 2023-10-18 07:46 UTC by FanManutd

closes #386

2023-10-30 17:46 UTC, iatsdotfatr commented
Как мне кажется, сама тема в текущем состоянии очень поверхностна. Предлагаю тебе ознакомиться со статьями [раз](https://habr.com/ru/companies/yandex/articles/718084/) и [два](https://habr.com/ru/articles/517594/), и как минимум расширить вопрос про event loop (style, layout, paint, composite, очереди, связь с частотой обновления экрана) и добавить задачи из статьи, и, по возможности, добавить другие вопросы, если такие появятся по ходу прочтения.

2023-10-31 05:21 UTC, FanManutd commented
> Как мне кажется, сама тема в текущем состоянии очень поверхностна. Предлагаю тебе ознакомиться со статьями [раз](https://habr.com/ru/companies/yandex/articles/718084/) и [два](https://habr.com/ru/articles/517594/), и как минимум расширить вопрос про event loop (style, layout, paint, composite, очереди, связь с частотой обновления экрана) и добавить задачи из статьи, и, по возможности, добавить другие вопросы, если такие появятся по ходу прочтения.

Спасибо, ознакомлюсь)

2023-10-31 12:27 UTC, FanManutd commented
@iatsdotfatr Классные статьи)

На их основе расширил вопросы про Event loop и добавил две задачки из статьи.

Ещё немного переделал ресурсы: 
- добавил те статьи, что ты скинул
- Убрал две статьи мотивирующие использовать `async/await`. Как я понял, это из времён когда этот синтаксис был в новинку и людей надо было мотивировать на переход. По моему это уже не актуально. Да и в одной из уже имеющейся статей в ресурах так же затронуты преимущества `async/await`.
- Убрал на мой взгляд ненужную статью про Event loop в nodejs.

2023-11-04 08:41 UTC, Geksanit approved these changes

2023-11-07 07:32 UTC, iatsdotfatr requested changes

2023-11-07 08:25 UTC, FanManutd commented on frontend/middle-1/async.md
> +  * Как Event loop связан с частотой обновления экрана? Может ли браузер выполнить несколько макрозадач (задачи из Callback Queue) за один тик?
Ну да, "тик" тут не уместен. Вообще отсылка к тому, что браузер может выполнять макрозадачи подряд, пока не пройдёт 16.6мс (при 60 FPS). Тогда наверно лучше сформулировать "за одну итерацию цикла?"?

2023-11-07 08:29 UTC, FanManutd commented on frontend/middle-1/async.md
> +* На сайте есть ссылка с CSS `:hover { cursor: pointer }` и кнпопка с CSS `:hover { background-color: другой-цвет }`. А так же скрипт с бесконечным циклом `while(true);`. Вопрос: Что будет если навес
Угу, так лучше, спасибо)

2023-11-08 14:27 UTC, iatsdotfatr commented on frontend/middle-1/async.md
> +  * Как Event loop связан с частотой обновления экрана? Может ли браузер выполнить несколько макрозадач (задачи из Callback Queue) за один тик?
Это одно и то же. Задача же не прерывается, если не укладывается в 16.6, она продолжается, а интерфейс тормозит. Думаю, должно быть достаточно существующего вопроса про частоту обновления экрана и цикл.

2023-11-09 06:09 UTC, FanManutd commented on frontend/middle-1/async.md
> +  * Как Event loop связан с частотой обновления экрана? Может ли браузер выполнить несколько макрозадач (задачи из Callback Queue) за один тик?
Да, если задача выполняется дольше 16,6 мс, она продолжит выполняться до тех пор, пока не завершится.

Но если задача выполняется меньше 16,6 мс, то при соблюдении определённых условий, движок может сразу взять на выполнение следующую задачу из очереди макрозадач. И вопрос именно для этого кейса. Я например раньше думал, что на одну итерацию одна макрозадача при любых условиях. Мне кажется это хороший кейс и вопрос.

2023-11-10 17:32 UTC, iatsdotfatr commented on frontend/middle-1/async.md
> +  * Как Event loop связан с частотой обновления экрана? Может ли браузер выполнить несколько макрозадач (задачи из Callback Queue) за один тик?
Выполнение задачи это и есть одна итерация.

2023-11-13 06:56 UTC, FanManutd commented on frontend/middle-1/async.md
> +  * Как Event loop связан с частотой обновления экрана? Может ли браузер выполнить несколько макрозадач (задачи из Callback Queue) за один тик?
Хм, давай разбираться. У нас есть бесконечный цикл. Один проход по циклу - это одна итерация цикла. 
![image](https://github.com/fullstack-development/developers-roadmap/assets/90761929/cfbd2809-cb85-43e5-b357-d8372997d8ed)

За одну итерацию движок выполняет макрозадачи, микрозадачи, rAF и задачи отрисовки style, layout paint, composite. Наверно в статье меня сбила формулировка, что если после выполнения макрозадачи у нас нет микрозадач и задач отрисовки, то движок сразу выполнит следующую макрозадачу:

![image](https://github.com/fullstack-development/developers-roadmap/assets/90761929/ddb25fda-aa8f-4108-abf5-931e9f26064b)

И тут как бы вопрос, он берёт следующую макрозачачу в рамках этой же итерации или так как задач в других очередях нет, то просто запускает следующую итерацию и точно так же берёт следующую макрозадачу. Но пожалуй для нас де факто это не имеет значения, так как поведение тоже самое.

2023-11-13 07:00 UTC, FanManutd commented on frontend/middle-1/async.md
> +  * Как Event loop связан с частотой обновления экрана? Может ли браузер выполнить несколько макрозадач (задачи из Callback Queue) за один тик?
Думаю вопрос и правда не имеет смысла, убрал.

2023-11-13 10:17 UTC, Azmodan95 commented on frontend/middle-1/async.md
> +* На сайте есть ссылка с CSS `:hover { cursor: pointer }` и кнпопка с CSS `:hover { background-color: другой-цвет }`. А так же скрипт с бесконечным циклом `while(true);`. Вопрос: Что будет если навес
Тут вообще не понятно, в чем суть вопроса. Если есть бесконечный цикл, мы ведь вообще не увидим ни ссылки, ни кнопки. Страница тупо зависнет. Разве не так?

2023-11-13 10:21 UTC, FanManutd commented on frontend/middle-1/async.md
> +* На сайте есть ссылка с CSS `:hover { cursor: pointer }` и кнпопка с CSS `:hover { background-color: другой-цвет }`. А так же скрипт с бесконечным циклом `while(true);`. Вопрос: Что будет если навес
> Тут вообще не понятно, в чем суть вопроса. Если есть бесконечный цикл, мы ведь вообще не увидим ни ссылки, ни кнопки. Страница тупо зависнет. Разве не так?

Ссылку и кнопку увидим, но ховеры не сработают из-за бесконечного цикла (Event loop просто не дойдёт до этапа отрисовки). В этом и суть вопроса, что бы понимать, как Event Loop связан с отрисовкой сайта в браузере.

2023-11-13 10:27 UTC, Azmodan95 commented on frontend/middle-1/async.md
> +* На сайте есть ссылка с CSS `:hover { cursor: pointer }` и кнпопка с CSS `:hover { background-color: другой-цвет }`. А так же скрипт с бесконечным циклом `while(true);`. Вопрос: Что будет если навес
> > Тут вообще не понятно, в чем суть вопроса. Если есть бесконечный цикл, мы ведь вообще не увидим ни ссылки, ни кнопки. Страница тупо зависнет. Разве не так?
> 
> Ссылку и кнопку увидим, но ховеры не сработают из-за бесконечного цикла (Event loop просто не дойдёт до этапа отрисовки). В этом и суть вопроса, что бы понимать, как Event Loop связан с отрисовкой сайта в браузере.

Я только что проверил. Не вижу ни ссылки, ни кнопки. Просто белую страницу, не на что не реагирующую.

2023-11-13 10:33 UTC, FanManutd commented on frontend/middle-1/async.md
> +* На сайте есть ссылка с CSS `:hover { cursor: pointer }` и кнпопка с CSS `:hover { background-color: другой-цвет }`. А так же скрипт с бесконечным циклом `while(true);`. Вопрос: Что будет если навес
> Я только что проверил. Не вижу ни ссылки, ни кнопки. Просто белую страницу, не на что не реагирующую.

А можешь показать HTML, на котором проверял? А лучше в codepen какой нибудь

2023-11-13 10:54 UTC, iatsdotfatr commented on frontend/middle-1/async.md
> +* На сайте есть ссылка с CSS `:hover { cursor: pointer }` и кнпопка с CSS `:hover { background-color: другой-цвет }`. А так же скрипт с бесконечным циклом `while(true);`. Вопрос: Что будет если навес
Если `while(true);` запустится до отрисовки ссылки с кнопкой, то так и будет.

2023-11-13 10:54 UTC, iatsdotfatr approved these changes

2023-11-13 11:09 UTC, Azmodan95 commented on frontend/middle-1/async.md
> +* На сайте есть ссылка с CSS `:hover { cursor: pointer }` и кнпопка с CSS `:hover { background-color: другой-цвет }`. А так же скрипт с бесконечным циклом `while(true);`. Вопрос: Что будет если навес
Так может тогда, стоит переформулировать в корне вопрос, без этих условностей с наведением мыши на элемент. Так как это только путает, а вопрос то ведь совсем про другое.

2023-11-13 11:15 UTC, iatsdotfatr commented on frontend/middle-1/async.md
> +* На сайте есть ссылка с CSS `:hover { cursor: pointer }` и кнпопка с CSS `:hover { background-color: другой-цвет }`. А так же скрипт с бесконечным циклом `while(true);`. Вопрос: Что будет если навес
Как мне кажется, из вопроса понятно, что на странице уже есть ссылка и кнопка.

2023-11-13 13:39 UTC, Azmodan95 commented on frontend/middle-1/async.md
> +* На сайте есть ссылка с CSS `:hover { cursor: pointer }` и кнпопка с CSS `:hover { background-color: другой-цвет }`. А так же скрипт с бесконечным циклом `while(true);`. Вопрос: Что будет если навес
Допустим, что с ссылкой и кнопкой все понятно. Но суть вопроса, то ведь заключается в том, что будет, если запустить бесконечный цикл в однопоточном приложении. Зачем так завуалированно его задавать.

2023-11-13 13:51 UTC, FanManutd commented on frontend/middle-1/async.md
> +* На сайте есть ссылка с CSS `:hover { cursor: pointer }` и кнпопка с CSS `:hover { background-color: другой-цвет }`. А так же скрипт с бесконечным циклом `while(true);`. Вопрос: Что будет если навес
> Допустим, что с ссылкой и кнопкой все понятно. Но суть вопроса, то ведь заключается в том, что будет, если запустить бесконечный цикл в однопоточном приложении. Зачем так завуалированно его задавать.

Я бы не сказал, что он прям завуалирован, ведь вопрос находится в теме про асинхронность и задаётся в контексте Event Loop. 

Плюс это наглядный пример, что даже такие вещи как ховер всё равно обрабатываются движком JS, так как браузер помещает задачу в render queue. Мне нравится этот вопрос.

В конце концов он полностью взят из статьи, которая будет в ресурсах, так что проблем с ответом на него не должно быть.

2023-11-13 13:56 UTC, iatsdotfatr commented on frontend/middle-1/async.md
> +* На сайте есть ссылка с CSS `:hover { cursor: pointer }` и кнпопка с CSS `:hover { background-color: другой-цвет }`. А так же скрипт с бесконечным циклом `while(true);`. Вопрос: Что будет если навес
Наверное, имеет смысл сделать его подвопросом в контексте отрисовки.

2023-11-15 06:39 UTC, FanManutd commented on frontend/middle-1/async.md
> +* На сайте есть ссылка с CSS `:hover { cursor: pointer }` и кнпопка с CSS `:hover { background-color: другой-цвет }`. А так же скрипт с бесконечным циклом `while(true);`. Вопрос: Что будет если навес
@osyka-yuri поправил, глянь пожалуйста, так пойдёт?

2023-11-15 10:39 UTC, osyka-yuri approved these changes

2023-11-15 12:26 UTC, merged