Add new questions to CSS
fullstack-development/developers-roadmap pull request #402
Opened 2023-10-18 10:58 UTC by FanManutd

closes #391

2023-11-03 12:04 UTC, Geksanit requested changes

2023-11-03 12:04 UTC, Geksanit commented on frontend/junior-2/css.md
> +* Что означают следующие единицы измерения `lvh, svh, dvh, lvw, svw, lvw`?
поправь последнее lvw на dvw

2023-11-07 05:38 UTC, FanManutd commented on frontend/junior-2/css.md
> +* Что означают следующие единицы измерения `lvh, svh, dvh, lvw, svw, lvw`?
Спасибо, исправил

2023-11-09 17:32 UTC, Nikita-Zaitsev-ML commented on frontend/junior-2/css.md
> +* Что делают свойства `filter` и `backdrop-filter`?
сюда еще можно добавить `mix-blend-mode`

2023-11-09 17:48 UTC, Nikita-Zaitsev-ML commented
Что еще на мой взгляд было бы полезно добавить:

- в jun1:
  -  про новые цветовые пространства(`oklch` и т.д.): некоторые сайты уже переходят потихоньку на него;
  - уточнение в вопрос про трансформации что у них теперь есть отдельные свойства, а не только как функции `transform`
  - `conic-gradient`
  - `currentColor`
- в jun2:
  - вариативные шрифты;
  - `prefers-reduced-motion` и `prefers-color-scheme`;
  - `color-scheme`
- в jun3:
  - CSS Cascade Layers 
  - тригонометрические функции :D
  - `color-mix()`
- не знаю куда лучше:
  - css переменные(их нет до сих пор?)
  - `@supports`
  - `scrollbar-gutter `;
  - `overscroll-behavior`;
  - `touch-action`;
  - `line-clamp` - тут вообще про обрезку текста можно отдельный блок с различными способами обрезки их особенностями работы у них

2023-11-10 05:53 UTC, FanManutd commented
> Что еще на мой взгляд было бы полезно добавить:

Супер, давай заведём отдельное ишью, я к нему вернусь позже) А то мы щас увязнем с этим ПР.

@Nikita-Zaitsev-ML

2023-11-10 06:07 UTC, FanManutd commented on frontend/junior-2/css.md
> +* Что делают свойства `filter` и `backdrop-filter`?
Готово

2023-11-10 07:09 UTC, Nikita-Zaitsev-ML commented
> > Что еще на мой взгляд было бы полезно добавить:
> 
> Супер, давай заведём отдельное ишью, я к нему вернусь позже) А то мы щас увязнем с этим ПР.
> 
> @Nikita-Zaitsev-ML

назначил на тебя @FanManutd https://github.com/fullstack-development/developers-roadmap/issues/404

2023-11-10 07:12 UTC, Nikita-Zaitsev-ML approved these changes

2023-11-13 08:48 UTC, Geksanit approved these changes

2023-11-13 08:50 UTC, merged