*/react: add react v18 topics
fullstack-development/developers-roadmap pull request #416
Opened 2024-10-10 09:18 UTC by Nikita-Zaitsev-ML

closes #415

2024-10-10 10:12 UTC, Nikita-Zaitsev-ML commented
`<Suspense>` пока не стал добавлять так как использование для data fetching все еще не совсем public API: [рекомендация использовать только через фреймворки и обещание добавить в будущем примитивы для работы](https://react.dev/blog/2022/03/29/react-v18#suspense-in-data-frameworks), [примеры в доке все еще на костылях](https://react.dev/reference/react/Suspense#usage) - смотри код в playground-ах. Работу лишь с `React.lazy` и transitions считаю недостаточной для внедрения в нашу карту развития. Ждем полноценный релиз React 19. Пока можно будет поспрашивать в рамках вопросов про transitions.

Не знаю куда и стоит ли добавлять хук `useId`(тык)[https://react.dev/reference/react/useId]:  вроде полезно знать что его использование позволяет избежать проблем с расхождением между значениями на клиенте и сервере("the order in which the Client Components are hydrated may not match the order in which the server HTML was emitted"), особенно в разрезе работы streaming server renderer. И что не следует использовать для генерации `key`: в доке аж 2 раза об этом написали :D

2024-11-07 15:42 UTC, ivtarasov commented on frontend/junior-3/react.md
> +  * как сохранить внутренние состояния при размонтировании?
тут скорее всего надо заглавную букву сделать)

2024-11-07 15:49 UTC, ivtarasov reviewed
очень классные изменения и примеры, спасибо большое за проделанную работу!

как ты думаешь, стоит ли в рамках текущего пр что-то сделать с вопросом?
```
Всегда ли происходит перерисовка DOM-элемента, если shouldComponentUpdate вернул true?
```
можно его передвинуть повыше к группе вопросов про reconciliation, или вовсе задуматься над его актуальностью (исходя из сегодняшних обсуждений).

2024-11-07 17:39 UTC, Nikita-Zaitsev-ML commented on frontend/junior-3/react.md
> +  * как сохранить внутренние состояния при размонтировании?
Немного переделал формулировку

2024-11-07 17:42 UTC, Nikita-Zaitsev-ML commented
> как ты думаешь, стоит ли в рамках текущего пр что-то сделать с вопросом?
> 
> ```
> Всегда ли происходит перерисовка DOM-элемента, если shouldComponentUpdate вернул true?
> ```
> 
> можно его передвинуть повыше к группе вопросов про reconciliation, или вовсе задуматься над его актуальностью (исходя из сегодняшних обсуждений).

Я бы убрал совсем т.к. вопрос относится исключительно к методам жизненного цикла классовых компонентов. Посмотрим что коллеги скажут.

2024-11-08 11:09 UTC, ivtarasov approved these changes

2024-11-12 12:58 UTC, FanManutd commented on frontend/junior-1/react.md
> +  * Как управлять массивом ref-ов?
Не нашёл в доке упоминаний. Можешь пожалуйста написать о чём здесь речь? Может ссылки есть?

2024-11-12 12:58 UTC, FanManutd commented on frontend/junior-2/react.md
> +  * Какие группы пакетов по управлению состоянием существуют и какие проблемы каждая решает? Какие особенности реализации используются и какие ограничения из-за этого могут накладываться?
Я посмотрел видос, который ты дал в ресурсах. Если ты хотел составить какие-то вопросы по этому видосу, то видос гораздо более обзорный, а вопросы здесь получились довольно глубокими. 

Первые два вопроса "Какие группы пакетов... и какие проблемы решает?" в целом довольно обзорные и на них можно ответить после просмотра видоса. Вторая же часть с особенностями реализации и ограничениями уже гораздо серьёзнее. Обычно такие знания приобретаются либо после плотной работы с несколькими стейт менеджерами, либо в целом при наличии большого опыта в разработке и насмотренности. 

Я бы на 2го джуна оставил бы только первую часть и ссылку на видос. А вот вторую часть либо на мидла переносить, либо убрать, либо может ещё что-то с этим с делать.

Кстати первую часть вопроса я бы чуть чуть переформулировал. Не "Какие группы пакетов по управлению состоянием существуеют", а "Какие группы стейт менеджеров существуют?".

P.S. Сам видос топ.

2024-11-12 12:58 UTC, FanManutd commented on frontend/junior-2/react.md
> +  * Каков алгоритм организации состояния в react при декларативном программировании?
А что ты тут хочешь услышать?

2024-11-12 12:58 UTC, FanManutd commented on frontend/junior-2/react.md
> +  * В какой момент может выполниться эффект и функция очистки?
У нас на 1м джуне есть вопрос:

- Что такое массив зависимостей? Рассказать как он влияет на работу хука на примере useEffect (в том числе на возвращаемое колбэком значение).

Обычно тут я и спрашиваю человека о том, когда выполняется эффект и функция очистки. Прошу его явно проговорить, что функция очистки выполняется после ререндера при обновлении зависимостей в том числе. Ты же про это здесь хотел услышать? 

Я предлагаю твой вопрос убрать отсюда и улучшить формулировку на 1м джуне:

- Что такое массив зависимостей? Как он влияет на работу `useEffect`?
- Что может возвращать колбэк, передаваемый в `useEffect`?
- Когда выполняется функция очистки (cleanup function)?

2024-11-27 12:07 UTC, FanManutd commented
> > как ты думаешь, стоит ли в рамках текущего пр что-то сделать с вопросом?
> > ```
> > Всегда ли происходит перерисовка DOM-элемента, если shouldComponentUpdate вернул true?
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > можно его передвинуть повыше к группе вопросов про reconciliation, или вовсе задуматься над его актуальностью (исходя из сегодняшних обсуждений).
> 
> Я бы убрал совсем т.к. вопрос относится исключительно к методам жизненного цикла классовых компонентов. Посмотрим что коллеги скажут.

Этот вопрос появился из объяснения того, как работает алгоритм согласования в [старой доке](https://ru.legacy.reactjs.org/docs/optimizing-performance.html#shouldcomponentupdate-in-action). Там на примере `shouldComponentUpdate` показано, что даже если этот метод вернул true, то есть мы просим перерисовать элемент, React дополнительно сравнит результаты рендера и если они окажутся одинаковыми, то перерисовка в браузере не выполнится. Вопрос в том, работает ли тоже самое для `React.memo`? Единственное, что я нашёл в новой доке, использование `shouldComponentUpdate` аналогично использованию `React.memo` ([тыкните](https://react.dev/reference/react/Component#shouldcomponentupdate-caveats) и гляньте на сноску Note). Но про поведение описанное выше ни слова. Двоякая история. С одной стороны вопрос можно было бы адаптировать под `React.memo`, но эта информация есть только в старой доке на примере классовых компонентов.

2024-11-27 12:08 UTC, FanManutd commented
Можно добавить хук `useId` на 2го джуна.

P.S. В гитхабе можно создать тред без комментирования конкретных строк кода? Плодить кучу комментариев с ответами на ответы неудобно.

2024-11-27 12:30 UTC, FanManutd commented on frontend/junior-3/react.md
> +  * Как сбросить внутренние состояния компонента?
Ты наверно имеешь ввиду как родителю сбросить состояние дочернего компонента? Если да, то формулировка требует уточнения.

2024-11-27 12:30 UTC, FanManutd commented on frontend/junior-3/react.md
> +  * Как сохранить внутренние состояния для последующего использования при необходимости скрыть результат рендера?
Здесь наверно та же история? Родителю сохранить состояние дочернего компонента? 

И я бы убрал "для последующего использования". Как буд-то это логично, но при этом ухудшает читаемость вопроса.

2024-11-28 12:53 UTC, Nikita-Zaitsev-ML commented on frontend/junior-1/react.md
> +  * Как и для чего использовать хуки `useRef` и `useImperativeHandle`?
Я бы сказал, что лучше отстреляться с рефами прямо здесь т.к. на отдельный вопрос как-то не тянет, а в топиках jun-2/jun-3 про рефы ничего нет. Сам подход не то чтобы сильно мудреный и прямо вытекает из понимания рефов.

В [доке](https://react.dev/learn/manipulating-the-dom-with-refs#exposing-a-subset-of-the-api-with-an-imperative-handle) хук прямо в разделе рефов.

2024-11-28 12:54 UTC, Nikita-Zaitsev-ML commented on frontend/junior-1/react.md
> +  * Как управлять массивом ref-ов?
https://react.dev/learn/manipulating-the-dom-with-refs#how-to-manage-a-list-of-refs-using-a-ref-callback

2024-11-28 13:00 UTC, Nikita-Zaitsev-ML commented on frontend/junior-2/react.md
> +  * Каков алгоритм организации состояния в react при декларативном программировании?
https://react.dev/learn/reacting-to-input-with-state#thinking-about-ui-declaratively

2024-11-28 13:48 UTC, Nikita-Zaitsev-ML commented on frontend/junior-2/react.md
> +  * В какой момент может выполниться эффект и функция очистки?
https://react.dev/reference/react/useEffect#caveats - caused by an interaction 2 пункта

2024-11-28 13:54 UTC, Nikita-Zaitsev-ML commented on frontend/junior-2/react.md
> +  * В какой момент может выполниться эффект и функция очистки?
в jun-1 формулировки поменял, но "Когда выполняется функция очистки (cleanup function)?" не стал добавлять т.к. я думаю лучше в jun-2 этот вопрос оставить

2024-11-28 13:54 UTC, Nikita-Zaitsev-ML commented on frontend/junior-1/react.md
> +  * Какие существуют правила при работе с хуками?
исправлено

2024-11-28 13:54 UTC, Nikita-Zaitsev-ML commented on frontend/junior-2/react.md
> +  * Какие группы пакетов по управлению состоянием существуют и какие проблемы каждая решает? Какие особенности реализации используются и какие ограничения из-за этого могут накладываться?
Исправил.
Но вторую часть вопроса все равно буду спрашивать как офф топик при приемке. Так сказать "на подумать")

2024-11-28 14:08 UTC, Nikita-Zaitsev-ML commented on frontend/junior-2/react.md
> +  * Для чего предназначены хуки `useLayoutEffect`, `useInsertionEffect`, `useSyncExternalStore`?
Вопрос достаточно мягкий: я не жду от ответа что мне расскажут про полную сигнатуру и глубокие особенности работы. Достаточно лишь знать что такие штуки вообще есть и когда надо - вспомнить о них. 

Вообще, react team идет к тому, чтобы полностью отказаться от `useEffect`(где-то видел что они писали об этом) - постепенно добавят специфичные хуки, заточенные под конкретные кейсы. Идея в том - чтобы в конечном итоге вообще не использовать `useEffect` т.к., по их мнению, - это источник багов в приложении.

Конкретно `useSyncExternalStore` призвано по сути заменить основной use case `useEffect` - обеспечить синхронизацию с внешними системами: network, third-party libs, DOM, глобальными значениями(aka `navigator.onLine`).

`useInsertionEffect` может действительно супер специфичен, но знать о том что он единственный не вызовет layout т.к. вызывается до вставки в DOM  react-ом выглядит полезным.

В дальнейшем в этот вопрос можно будет добавлять и другие заменители `useEffect`

2024-11-28 14:17 UTC, Nikita-Zaitsev-ML commented on frontend/junior-2/react.md
> +  * Почему использовать `fetch` в `useEffect` - не самая хорошая идея? Какие есть альтернативы?
>Эта формулировка может заставить думать буд-то в Реакте есть другие способы вызвать запрос данных, кроме как в useEffect.

есть - через `use`. Фреймворки реализацию делают не на `useEffect`, а используя особенности всплытия для `<Suspense>`

В частности это позволяет не рендерить компонент пока внутри него все suspended запросы не выполнились - такие компоненты оборачиваем в `<Suspense>`.

тут подробнее: https://react.dev/reference/react/useEffect#what-are-good-alternatives-to-data-fetching-in-effects

вот как это работает в Jotai: https://jotai.org/docs/core/atom#advanced-api - там и примерчик внизу есть. https://jotai.org/docs/utilities/async - так можно обрабатывать привычным образом, без Suspense т.к. suspended компоненты вызывают useMemo, useRef повторно когда переходят в данное состояние(динамически атомы не посоздаёшь)

2024-11-28 14:24 UTC, Nikita-Zaitsev-ML commented on frontend/junior-2/react.md
> +* Как отрендерить разный контент между клиентом и сервере и не нарушить процесс гидратации?
вынес в mid-1

2024-11-28 14:30 UTC, Nikita-Zaitsev-ML commented
> > > как ты думаешь, стоит ли в рамках текущего пр что-то сделать с вопросом?
> > > ```
> > > Всегда ли происходит перерисовка DOM-элемента, если shouldComponentUpdate вернул true?
> > > ```
> > > можно его передвинуть повыше к группе вопросов про reconciliation, или вовсе задуматься над его актуальностью (исходя из сегодняшних обсуждений).
> > 
> > 
> > Я бы убрал совсем т.к. вопрос относится исключительно к методам жизненного цикла классовых компонентов. Посмотрим что коллеги скажут.
> 
> Этот вопрос появился из объяснения того, как работает алгоритм согласования в [старой доке](https://ru.legacy.reactjs.org/docs/optimizing-performance.html#shouldcomponentupdate-in-action). Там на примере `shouldComponentUpdate` показано, что даже если этот метод вернул true, то есть мы просим перерисовать элемент, React дополнительно сравнит результаты рендера и если они окажутся одинаковыми, то перерисовка в браузере не выполнится. Вопрос в том, работает ли тоже самое для `React.memo`? Единственное, что я нашёл в новой доке, использование `shouldComponentUpdate` аналогично использованию `React.memo` ([тыкните](https://react.dev/reference/react/Component#shouldcomponentupdate-caveats) и гляньте на сноску Note). Но про поведение описанное выше ни слова. Двоякая история. С одной стороны вопрос можно было бы адаптировать под `React.memo`, но эта информация есть только в старой доке на примере классовых компонентов.

В Note сказано "is similar" - то есть "похоже" - речь скорее про то, что мы можем управлять будет ли перерисован компонент. Сам по себе shouldComponentUpdate имеет отношение только к жизненному циклу классовых компонентов, которые работают несколько иначе, чем функциональные.

Все еще думаю, что можно убрать вопрос из-за неактуальности

2024-11-28 14:46 UTC, Nikita-Zaitsev-ML commented on frontend/junior-3/react.md
> +  * Как сбросить внутренние состояния компонента?
исправлено на "Как сбросить внутренние состояния дочернего компонента?"

2024-11-28 14:46 UTC, Nikita-Zaitsev-ML commented on frontend/junior-3/react.md
> +  * Как сохранить внутренние состояния для последующего использования при необходимости скрыть результат рендера?
исправлено на "Как сохранить внутренние состояния дочернего компонента при необходимости скрыть результат рендера?"

2024-12-04 08:36 UTC, FanManutd commented on frontend/junior-1/react.md
> +  * Как управлять массивом ref-ов?
Давай уточним вопрос конкретным примером. "Допустим вам необходимо передать ref в каждый элемент списка, но вы не знаете заранее сколько элементов в этом списке может быть. Как поступить в таком случае?".

И дать ссылку на эту инфу в ресурсах.

2024-12-04 08:37 UTC, FanManutd commented on frontend/junior-1/react.md
> +  * Как и для чего использовать хуки `useRef` и `useImperativeHandle`?
Окей.

2024-12-04 08:41 UTC, FanManutd commented on frontend/junior-2/react.md
> +  * Какие группы пакетов по управлению состоянием существуют и какие проблемы каждая решает? Какие особенности реализации используются и какие ограничения из-за этого могут накладываться?
> Но вторую часть вопроса все равно буду спрашивать как офф топик при приемке. Так сказать "на подумать")

Окей)

Осталось убрать ссылки на сравнения разных стейт менеджеров. Оставить только ссылку на видос.

2024-12-04 16:29 UTC, Nikita-Zaitsev-ML commented on frontend/junior-1/react.md
> +  * Как управлять массивом ref-ов?
Сделано.

2024-12-04 16:29 UTC, Nikita-Zaitsev-ML commented on frontend/junior-2/react.md
> +  * Какие группы пакетов по управлению состоянием существуют и какие проблемы каждая решает? Какие особенности реализации используются и какие ограничения из-за этого могут накладываться?
Сделано

2024-12-12 09:26 UTC, FanManutd commented on frontend/junior-2/react.md
> +  * Каков алгоритм организации состояния в react при декларативном программировании?
Давай оставим ссылку на это в ресурсах.

2024-12-12 09:32 UTC, FanManutd commented on frontend/middle-1/rendering.md
>  * Какие зоны ответственности у front-server, API-server и непосредственно самого клиента в изоморфном рендеринге? Какие вычислительные нагрузки ложатся на каждую из этих частей?
Если не сложно, давай вопрос про зоны ответственности перенесём выше вопроса про гидратацию. 

Один из разработчиков во время сдачи посетовал, что вопросы разделены гидратацией. Как буд-то бы логично закончить про виды рендеринга и про изоморфный рендеринг и уже после этого спрашивать про гидратацию.

2024-12-12 09:33 UTC, FanManutd commented on frontend/middle-1/rendering.md
> +  * Как отрендерить разный контент между клиентом и сервере и не нарушить процесс гидратации?
Опечатка "между клиентом и сервером"

2024-12-12 09:40 UTC, FanManutd commented on frontend/junior-3/react.md
>    * Всегда ли происходит перерисовка DOM-элемента, если `shouldComponentUpdate` вернул `true`?
Давай выпилим вопрос про `shouldComponentUpdate`. К сожалению я не нахожу подтверждения того, что в функциональных компонентах поведение такое же как в классовых. Если `shouldComponentUpdate` возвращает `true`, то Реакт дополнительно сравнит результат предыдущего рендера и нового и если они совпали, то не будет перериросывать компонент. А вот в случае со вторым параметром `React.memo()`, если коллбэк вернёт `false`, то есть мы фактически говорим Реакту, что компонент нужно обновить, непонятно, будет ли перерисовка при одинаковом результате предыдущего и нового рендера, или нет. 

Можно конечно самому проверить, ради интереса, но ссылку на ресурсы тут пока не дать.

2024-12-12 09:57 UTC, FanManutd commented on frontend/junior-2/react.md
> +  * Для чего предназначены хуки `useLayoutEffect`, `useInsertionEffect`, `useSyncExternalStore`?
Убедил

2024-12-12 10:11 UTC, FanManutd commented on frontend/junior-2/react.md
> +  * Почему использовать `fetch` в `useEffect` - не самая хорошая идея? Какие есть альтернативы?
> тут подробнее: https://react.dev/reference/react/useEffect#what-are-good-alternatives-to-data-fetching-in-effects

Отличная ссылка, давай добавим её в ресурсы. И я закрою тред.

2024-12-12 10:36 UTC, FanManutd commented on frontend/junior-3/react.md
> +    ```jsx
Давай спрячем примеры под `details`, как это сделано [здесь](https://github.com/fullstack-development/developers-roadmap/blob/fc4c0924c59214aa8a8fa4dc549eaa25e223c78a/frontend/junior-2/ts.md?plain=1#L69).

2024-12-12 10:36 UTC, FanManutd commented on frontend/junior-3/data.md
> +* Какие способы обновить глубоко вложенное значение есть? Что можно сделать, чтобы не было необходимости работать с глубоко вложенными значениями?
Долго думал, что меня здесь смущает. 

Я же правильно понимаю, что ты хочешь услышать не просто про обновление глубоко вложенных значений, а про обновление данных без мутации? 

Тут два подхода, рассказать об этом в контексте Реакта (useState, стейт менеджеры) или в контексте JS в целом. 

Если в контексте JS, то да, стоит оставить этот вопрос в теме "Работа с данными", но дать другие ресурсы, не связанные никак с Реакт. 

Если хочется послушать в контексте Реакта, то перенести этот вопрос в один из топиков по Реакту и оставить текущие ресурсы.

2024-12-12 11:35 UTC, Nikita-Zaitsev-ML commented on frontend/junior-2/react.md
> +  * Каков алгоритм организации состояния в react при декларативном программировании?
Сделано

2024-12-12 11:35 UTC, Nikita-Zaitsev-ML commented on frontend/junior-2/react.md
> +  * Почему использовать `fetch` в `useEffect` - не самая хорошая идея? Какие есть альтернативы?
Сделано

2024-12-12 11:35 UTC, Nikita-Zaitsev-ML commented on frontend/middle-1/rendering.md
>  * Какие зоны ответственности у front-server, API-server и непосредственно самого клиента в изоморфном рендеринге? Какие вычислительные нагрузки ложатся на каждую из этих частей?
Сделано

2024-12-12 11:35 UTC, Nikita-Zaitsev-ML commented on frontend/middle-1/rendering.md
> +  * Как отрендерить разный контент между клиентом и сервере и не нарушить процесс гидратации?
Исправлено

2024-12-12 11:36 UTC, Nikita-Zaitsev-ML commented on frontend/junior-3/react.md
>    * Всегда ли происходит перерисовка DOM-элемента, если `shouldComponentUpdate` вернул `true`?
Выпилено

2024-12-12 11:36 UTC, Nikita-Zaitsev-ML commented on frontend/junior-3/react.md
> +    ```jsx
Сделано

2024-12-12 11:45 UTC, Nikita-Zaitsev-ML commented on frontend/junior-3/data.md
> +* Какие способы обновить глубоко вложенное значение есть? Что можно сделать, чтобы не было необходимости работать с глубоко вложенными значениями?
> Я же правильно понимаю, что ты хочешь услышать не просто про обновление глубоко вложенных значений, а про обновление данных без мутации? Может так и сформулировать?

Не совсем: хочется именно услышать что хоть через мутации обновлять и можно, но делать так не следует, т.к. это сказывается на отслеживаемости изменений. Отдельно можно отметить, что мутировать, если мы только создаём объект, в целом можно(имеется ввиду в рамках некой функции создания какой-то сложной структуры).

Далее следует предложить альтернативы: 
* spread синтаксис, - отметить что очень многословный, хоть и рабочий. Что есть мутирующие и не мутирующие методы массивов и для изменения элементов-объектов таких массивов тоже надо не мутировать, а пересоздавать объекты с измененными полями(например 2 списка, начальные данные которых идентичны - тут при изменении как каждый объект следует пересоздавать чтобы рисовать элементы между списками независимо);
* immer.js с его draft-ами на proxy;
* ramda/optics-ts, которые позволяют менять конкретные поля без пересоздания объекта, на котором сфокусировались(ссылка останется прежней)

2024-12-12 11:46 UTC, Nikita-Zaitsev-ML commented on frontend/junior-3/data.md
> +* Какие способы обновить глубоко вложенное значение есть? Что можно сделать, чтобы не было необходимости работать с глубоко вложенными значениями?
> Тут два подхода, рассказать об этом в контексте Реакта (useState, стейт менеджеры) или в контексте JS в целом.

Вопрос поместил именно в data т.к. для react есть вопросы про управление стейтом приложения, а тут именно чисто про объекты

2024-12-12 11:48 UTC, Nikita-Zaitsev-ML commented on frontend/junior-3/data.md
> +* Какие способы обновить глубоко вложенное значение есть? Что можно сделать, чтобы не было необходимости работать с глубоко вложенными значениями?
> Если хочется послушать в контексте Реакта, то перенести этот вопрос в один из топиков по Реакту и оставить текущие ресурсы.

Ресурсы хоть и реактовские, но больше не про особенности react, а просто проблему обновления вложенных данных и способы решения.

2024-12-12 11:53 UTC, FanManutd commented on frontend/junior-3/react.md
> +  * Как вызвать немедленное обновление состояний компонента внутри `callback`? Когда это может быть полезно?
Мы же говорим про батчинг состояния в Реакт? Доклад в ресурсах раскрывает только тему батчинга состояния при асинхронных обработчиках в Реакт 18. Интересно, что автор ни слова не сказал про то, что с 18го реакта батчатся не только обработчики синтетик ивентов, а в принципе все апдейты состояний, где бы их не вызвали. Вот [ссылка](https://react.dev/blog/2022/03/08/react-18-upgrade-guide#automatic-batching), думаю стоит дать её в ресурсах.

Непонятен вопрос "Что для этого нужно?". Разве вопрос "В каких случая происходит?" не одно и то же? Или о чём тут речь?

Ещё непонятен вопрос `Когда следует задумываться о необходимости такой оптимизации?`. Если мы говорим о Реакт, разве у нас есть выбор? Реакт батчит все состояния которые может. Мы можем только отказаться от этого с помощью `flushSync`, что упоминается в следующем вопросе.

2024-12-12 12:06 UTC, Nikita-Zaitsev-ML commented on frontend/junior-3/react.md
> +  * Как вызвать немедленное обновление состояний компонента внутри `callback`? Когда это может быть полезно?
>Мы же говорим про батчинг состояния в Реакт? Доклад в ресурсах раскрывает только тему батчинга состояния при асинхронных обработчиках в Реакт 18. Интересно, что автор ни слова не сказал про то, что с 18го реакта батчатся не только обработчики синтетик ивентов, а в принципе все апдейты состояний, где бы их не вызвали. Вот [ссылка](https://react.dev/blog/2022/03/08/react-18-upgrade-guide#automatic-batching), думаю стоит дать её в ресурсах.

Ссылку добавил. 

>Непонятен вопрос "Что для этого нужно?". Разве вопрос "В каких случая происходит?" не одно и то же? Или о чём тут речь?

нужно: до v18 - `unstable_batchedUpdates`, после - `createRoot` вместо `render` из react-dom

> Ещё непонятен вопрос Когда следует задумываться о необходимости такой оптимизации?. Если мы говорим о Реакт, разве у нас есть выбор? Реакт батчит все состояния которые может. Мы можем только отказаться от этого с помощью flushSync, что упоминается в следующем вопросе.

От ответа я ожидаю что-то типа: оптимизация ререндеров на практике даёт не особо большой прирост производительности т.к. при перерисовке небольших частей это быстро, а если часто перерисовываешь что-то больше - то у тебя проблемы с архитектурой и надо править её. Ну и как же без упоминания что сначала лезем в профайлер в случае тормозов или другой плохой оптимизации.

2024-12-12 12:27 UTC, FanManutd commented on frontend/junior-3/react.md
> +  * Как вызвать немедленное обновление состояний компонента внутри `callback`? Когда это может быть полезно?
Я как раз про то, что только до v18 мы могли самостоятельно заниматься оптимизацией путём батчинга и тогда вопрос о том когда стоит это делать имел смысл. После v18 это не актуально, `render` вообще удалён из React 19. 

Я бы не хотел оставлять вопросы в карте развития связанные со старым поведением. Да, это пригодится на легаси проектах, но оно не стоит того, что бы оставлять это в карте.

2024-12-13 06:23 UTC, Nikita-Zaitsev-ML commented on frontend/junior-3/react.md
> +  * Как вызвать немедленное обновление состояний компонента внутри `callback`? Когда это может быть полезно?
вопросы "Что для этого нужно?" и "Когда следует задумываться о необходимости такой оптимизации?" удалены

2024-12-16 12:47 UTC, FanManutd commented on frontend/junior-3/react.md
> +    * Будет ли заново монтироваться компонент `<Input id="3" />`, если я добавлю/удалю что-то в массиве `data`?
Давай добавим ссылку на [прекрасную статью](https://gist.github.com/zagazat/db926ec7ab69061934246a55b64913c3), откуда это взято.

2024-12-16 13:29 UTC, Nikita-Zaitsev-ML commented on frontend/junior-3/data.md
> +* Какие способы обновить глубоко вложенное значение есть? Что можно сделать, чтобы не было необходимости работать с глубоко вложенными значениями?
Исправлено

2024-12-20 14:06 UTC, Everrest1 commented on frontend/junior-3/react.md
> +        }
По-моему тут закрывающая скобка не в том месте, должна быть после return

2024-12-20 14:10 UTC, Everrest1 commented on frontend/junior-3/react.md
> +    * Произойдет ли сброс состояния `Counter`? Почему?
Мне кажется, чтобы отмести сомнения, стоит уточнить вопрос "Произойдет ли сброс состояния `Counter` _при изменении значения IsFancy на true_? Почему?" Если именно это имелось ввиду, я лично не уверен

2024-12-20 18:14 UTC, Nikita-Zaitsev-ML commented on frontend/junior-3/react.md
> +        }
Исправлено

2024-12-20 18:14 UTC, Nikita-Zaitsev-ML commented on frontend/junior-3/react.md
> +    * Произойдет ли сброс состояния `Counter`? Почему?
Сделано

2024-12-20 18:14 UTC, Nikita-Zaitsev-ML commented on frontend/junior-3/react.md
> +    * Будет ли заново монтироваться компонент `<Input id="3" />`, если я добавлю/удалю что-то в массиве `data`?
Добавлено

2024-12-23 06:41 UTC, alagunoff requested changes

2024-12-23 06:41 UTC, alagunoff commented on frontend/junior-1/react.md
> +  * Что такое декларативное UI программирование? Чем оно отличается от императивного подхода?
Мне кажется вопрос довольно абстрактный, чтобы быть в топике реакт и в вопросе про вид компонента. Может подумать над созданием топика типо "Общие темы"?

2024-12-23 06:41 UTC, alagunoff commented on frontend/junior-1/react.md
> +  * Для чего не должен использоваться `useEffect`? Почему?
Я бы добавил вопрос "useEffect" сразу же после вопроса "Lifecycle of reactive effects", куда занёс бы вопросы по useEffect. Мне кажется так более правильно

2024-12-23 06:59 UTC, FanManutd commented on frontend/junior-1/react.md
> +  * Что такое декларативное UI программирование? Чем оно отличается от императивного подхода?
Ну, вопрос очень даже в контексте React, ведь React и есть про декларативное UI программирование. Плюс он легко гуглится и хорошо считывается с документации, если ты читаешь документацию) 

А насчёт создания отдельного топика - то для этого нужно явно больше причин и более существенные. Пара вопросов ради одного топика, которые хорошо ложатся в уже существующие - не лучшая причина.

2024-12-23 07:05 UTC, FanManutd commented on frontend/junior-1/react.md
> +  * Для чего не должен использоваться `useEffect`? Почему?
Ты имеешь ввиду вопросы про `useEffect` сделать не вложенными в `Lifecycle of reactive effects`, а отдельной группой `useEffect`? 

Если да, то я не вижу большой разницы. Может у Никиты есть мнение.

2024-12-23 07:38 UTC, Nikita-Zaitsev-ML commented on frontend/junior-1/react.md
> +  * Для чего не должен использоваться `useEffect`? Почему?
> Ты имеешь ввиду вопросы про `useEffect` сделать не вложенными в `Lifecycle of reactive effects`, а отдельной группой `useEffect`?

Если предложение в этом, то мне требуются пояснительные детали чем это будет лучше. Сейчас блок "Lifecycle of reactive effects" мне кажется достаточно последовательным и хорошо связным, а при разбиении получится 2 блока по сути об одной сфере.

2024-12-23 07:46 UTC, Nikita-Zaitsev-ML commented on frontend/junior-1/react.md
> +  * Что такое декларативное UI программирование? Чем оно отличается от императивного подхода?
Вопрос был добавлен именно из-за бОльшего крена обновленной документации в примеры того как, по мнению разработчиков react-team, правильнее использовать react исходя из текущих и планируемых нововведений. 

Конкретно [статья документации](https://react.dev/learn/reacting-to-input-with-state#how-declarative-ui-compares-to-imperative) представляет исчерпывающие ответы на данные вопросы и позволяет лучше проникнуться духом вектора развития react.

Я бы сказал что вопрос больше для того, чтобы лучше понять react, а не про базовые навыки/принципы разработки - поэтому выносить куда-то отдельно не вижу смысла.

2024-12-24 07:44 UTC, alagunoff commented on frontend/junior-1/react.md
> +  * Что такое декларативное UI программирование? Чем оно отличается от императивного подхода?
> Я бы сказал что вопрос больше для того, чтобы лучше понять react, а не про базовые навыки/принципы разработки 

Если посмотреть на вопрос с этой стороны, то согласен. Но всё же, думаю вопрос не должен быть привязан к вопросу про вид компонента. Логичнее бы его разместить после первого вопроса про то, что такое реакт

Касаемо предложения, я не говорю, что вопрос *не* о реакт, я говорю, что вопрос *не только* о реакт

2024-12-24 07:50 UTC, alagunoff commented on frontend/junior-1/react.md
> +  * Для чего не должен использоваться `useEffect`? Почему?
Вопрос не актуален. Я немного не так понял название подтемы)

2025-01-29 13:23 UTC, FanManutd commented on frontend/junior-1/react.md
> +  * Что такое декларативное UI программирование? Чем оно отличается от императивного подхода?
> Но всё же, думаю вопрос не должен быть привязан к вопросу про вид компонента. Логичнее бы его разместить после первого вопроса про то, что такое реакт

Соглашусь, переместил после первого вопроса.

2025-01-29 13:26 UTC, alagunoff approved these changes

2025-01-29 13:26 UTC, merged